[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino, espidf
extra_scripts =
    pre:scripts/pio_prebuild.py
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
build_flags =
    -I include
    -DTWAI_TX_PIN=15
    -DTWAI_RX_PIN=16
    -DESP_IDF_LWIP_HOOK_FILENAME=\"lwip_hooks.h\"
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
board_build.sdkconfig_defaults = sdkconfig.defaults

[env:native]
platform = native
test_framework = unity
test_build_src = false
build_flags =
    -I include
