[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino, espidf
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
build_flags =
    -DTWAI_TX_PIN=5
    -DTWAI_RX_PIN=4
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
board_build.sdkconfig_defaults = sdkconfig.defaults
