#!/usr/bin/env python3
"""
Generate include/web_ui.h from ui/index.html + ui/styles.css + ui/app.js.
"""

from __future__ import annotations

from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
UI_DIR = ROOT / "ui"
INDEX_HTML_PATH = UI_DIR / "index.html"
STYLE_PATH = UI_DIR / "styles.css"
SCRIPT_PATH = UI_DIR / "app.js"
OUTPUT_PATH = ROOT / "include" / "web_ui.h"

STYLE_TAG_PATTERN = re.compile(
    r"""<link\b(?=[^>]*\brel=["']stylesheet["'])(?=[^>]*\bhref=["']\./styles\.css["'])[^>]*?/?>""",
    re.IGNORECASE,
)
SCRIPT_TAG_PATTERN = re.compile(
    r"""<script\b(?=[^>]*\bsrc=["']\./app\.js["'])[^>]*>\s*</script>""",
    re.IGNORECASE,
)


def load_text(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"Missing required file: {path}")
    return path.read_text(encoding="utf-8")


def build_html() -> str:
    html = load_text(INDEX_HTML_PATH)
    css = load_text(STYLE_PATH).strip()
    js = load_text(SCRIPT_PATH).strip()

    html, style_count = STYLE_TAG_PATTERN.subn(lambda _: f"<style>\n{css}\n</style>", html, count=1)
    if style_count != 1:
        raise ValueError(
            f"Missing stylesheet marker in {INDEX_HTML_PATH}: expected a link tag for ./styles.css"
        )

    html, script_count = SCRIPT_TAG_PATTERN.subn(lambda _: f"<script>\n{js}\n</script>", html, count=1)
    if script_count != 1:
        raise ValueError(
            f"Missing script marker in {INDEX_HTML_PATH}: expected a script tag for ./app.js"
        )

    if ")rawliteral\"" in html:
        raise ValueError("ui/index.html content contains rawliteral terminator, cannot embed safely.")

    return html.rstrip() + "\n"


def build_header(html: str) -> str:
    return (
        "#pragma once\n\n"
        "// Auto-generated from ui/index.html + ui/styles.css + ui/app.js\n"
        "// Do not edit this file manually. Run scripts/generate_web_ui_header.py instead.\n\n"
        "const char INDEX_HTML[] PROGMEM = R\"rawliteral(\n"
        f"{html}"
        ")rawliteral\";\n"
    )


def main() -> int:
    html = build_html()
    header = build_header(html)
    OUTPUT_PATH.write_text(header, encoding="utf-8")
    print(f"[ui] generated {OUTPUT_PATH.relative_to(ROOT)} from {UI_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # pragma: no cover - build script path
        print(f"[ui] generation failed: {exc}", file=sys.stderr)
        raise
