#pragma once

// Auto-generated from ui/index.html + ui/styles.css + ui/app.js
// Do not edit this file manually. Run scripts/generate_web_ui_header.py instead.

const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!doctype html>
<html lang="zh">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,user-scalable=no"
    />
    <title>FSD 控制器</title>
    <style>
:root{
  --bg:#050a14;
  --bg-soft:#0b1323;
  --panel:rgba(12,20,37,.92);
  --panel-strong:#121d33;
  --panel-soft:rgba(19,30,52,.76);
  --line:rgba(125,211,252,.16);
  --line-strong:rgba(125,211,252,.28);
  --text:#edf5ff;
  --muted:#90a7c7;
  --muted-strong:#c1d0e5;
  --accent:#e31937;
  --accent-strong:#ff4d67;
  --cyan:#5fd8ff;
  --green:#22c55e;
  --amber:#f59e0b;
  --red:#ef4444;
  --shadow:0 24px 70px rgba(0,0,0,.34);
}

*{margin:0;padding:0;box-sizing:border-box}
html,body{height:100%}
body{
  font-family:"PingFang SC","Microsoft YaHei",-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  background:
    radial-gradient(circle at 12% 10%,rgba(95,216,255,.16),transparent 28%),
    radial-gradient(circle at 88% 12%,rgba(227,25,55,.18),transparent 30%),
    linear-gradient(160deg,#040812 0%,#08101d 48%,#050a14 100%);
  color:var(--text);
  height:100svh;
  min-height:100vh;
  overflow:hidden;
  padding:12px;
}

.page{
  width:min(1400px,100%);
  height:calc(100svh - 24px);
  min-height:calc(100vh - 24px);
  margin:0 auto;
}

.app-shell{
  display:grid;
  grid-template-rows:auto minmax(0,1fr);
  gap:14px;
}

.topbar{
  display:flex;
  align-items:stretch;
  justify-content:space-between;
  gap:12px;
}

.brand-block,
.toolbar-btn,
.hero-card,
.live-item,
.dialog-sheet,
.picker-sheet{
  background:linear-gradient(180deg,rgba(20,32,54,.94) 0%,rgba(8,14,27,.96) 100%);
  border:1px solid var(--line);
  box-shadow:var(--shadow);
}

.brand-block{
  flex:1;
  min-width:0;
  border-radius:24px;
  padding:18px 22px;
  position:relative;
  overflow:hidden;
}

.brand-block:before,
.hero-card:before{
  content:"";
  position:absolute;
  inset:auto auto 0 0;
  width:160px;
  height:160px;
  background:radial-gradient(circle,rgba(95,216,255,.14),transparent 70%);
  pointer-events:none;
}

.brand-kicker,
.section-tag,
.card-title,
.metric-label,
.live-label,
.mini-stat-label,
.field-label{
  text-transform:uppercase;
  letter-spacing:1.6px;
}

.brand-kicker{
  font-size:11px;
  color:var(--cyan);
  opacity:.9;
}

h1{
  font-size:clamp(26px,4vw,40px);
  line-height:1.05;
  margin-top:8px;
  font-weight:800;
}

.page-subtitle{
  margin-top:10px;
  max-width:680px;
  font-size:13px;
  line-height:1.6;
  color:var(--muted);
}

.toolbar{
  width:min(760px,100%);
  display:grid;
  grid-template-columns:repeat(4,minmax(0,1fr));
  gap:10px;
}

.toolbar-btn{
  border:none;
  border-radius:20px;
  padding:14px 16px;
  color:var(--text);
  display:flex;
  flex-direction:column;
  justify-content:space-between;
  align-items:flex-start;
  gap:10px;
  cursor:pointer;
  transition:border-color .2s ease,transform .2s ease,background .2s ease;
}

.toolbar-btn:hover,
.toolbar-btn:focus-visible,
.secondary-btn:hover,
.secondary-btn:focus-visible,
.save-btn:hover:not(:disabled),
.upload-btn:hover:not(:disabled),
.ghost-btn:hover:not(:disabled),
.picker-trigger:hover:not(:disabled),
.picker-trigger:focus-visible,
.dialog-close:hover,
.dialog-close:focus-visible,
.file-btn:hover{
  border-color:var(--line-strong);
}

.toolbar-btn:hover,
.secondary-btn:hover,
.save-btn:hover:not(:disabled),
.upload-btn:hover:not(:disabled),
.ghost-btn:hover:not(:disabled),
.picker-trigger:hover:not(:disabled),
.file-btn:hover{
  transform:translateY(-1px);
}

.toolbar-btn:focus-visible,
.secondary-btn:focus-visible,
.save-btn:focus-visible,
.upload-btn:focus-visible,
.ghost-btn:focus-visible,
.picker-trigger:focus-visible,
.text-input:focus,
.dialog-close:focus-visible,
.file-btn:focus-visible{
  outline:none;
  box-shadow:0 0 0 2px rgba(95,216,255,.2);
}

.toolbar-label{
  font-size:15px;
  font-weight:700;
}

.toolbar-meta{
  width:100%;
  font-size:12px;
  color:var(--muted);
  white-space:nowrap;
  overflow:hidden;
  text-overflow:ellipsis;
}

.dashboard-main{
  min-height:0;
  display:grid;
  grid-template-columns:minmax(280px,.9fr) minmax(0,1.1fr);
  grid-template-rows:minmax(0,1fr) auto;
  gap:14px;
}

.hero-card{
  min-height:0;
  border-radius:28px;
  padding:18px;
  position:relative;
  overflow:hidden;
}

.section-tag{
  font-size:10px;
  color:var(--cyan);
  margin-bottom:14px;
}

.card-title{
  margin-bottom:10px;
  font-size:11px;
  color:var(--muted);
  font-weight:700;
}

.speed-card{
  display:flex;
  flex-direction:column;
  gap:10px;
}

.speed-card-head{
  display:flex;
  align-items:flex-start;
  justify-content:space-between;
  gap:12px;
}

.speed-card-head h2,
.metrics-head h2{
  font-size:clamp(26px,3vw,34px);
  line-height:1.08;
  font-weight:800;
}

.speed-card-head p,
.metrics-head p{
  margin-top:8px;
  font-size:13px;
  line-height:1.6;
  color:var(--muted);
}

.speed-card-head p{
  margin-top:6px;
  font-size:12px;
  line-height:1.45;
}

.hardware-pill{
  flex:0 0 auto;
  min-width:100px;
  text-align:center;
  padding:10px 14px;
  border-radius:999px;
  background:rgba(95,216,255,.12);
  border:1px solid rgba(95,216,255,.22);
  color:var(--cyan);
  font-size:12px;
  font-weight:700;
}

.speed-hero{
  display:grid;
  grid-template-columns:1fr;
  gap:12px;
}

.speed-quick{
  min-width:0;
  padding:14px 16px 16px;
  border-radius:22px;
  background:
    linear-gradient(135deg,rgba(227,25,55,.16),transparent 44%),
    linear-gradient(180deg,rgba(18,29,51,.96) 0%,rgba(10,16,30,.96) 100%);
  border:1px solid rgba(227,25,55,.2);
}

.speed-quick-label{
  font-size:12px;
  color:var(--muted);
  letter-spacing:1.2px;
}

.speed-quick-value{
  margin-top:6px;
  font-size:clamp(40px,5vw,58px);
  line-height:.95;
  font-weight:800;
  letter-spacing:-1.8px;
}

.speed-quick-note{
  margin-top:10px;
  font-size:13px;
  color:var(--muted-strong);
}

.hero-actions{
  display:grid;
  gap:10px;
}

.hero-controls{
  padding:12px;
  border-radius:22px;
  background:var(--panel-soft);
  border:1px solid rgba(125,211,252,.12);
}

.speed-card .row{
  padding:10px 0;
}

.speed-card .field{
  padding:10px 0 0;
}

.speed-offset-panel{
  display:grid;
  gap:10px;
}

.offset-grid{
  display:grid;
  grid-template-columns:repeat(6,minmax(0,1fr));
  gap:6px;
}

.offset-chip{
  min-height:40px;
  border-radius:12px;
  border:1px solid rgba(125,211,252,.12);
  background:rgba(19,33,58,.9);
  color:var(--muted-strong);
  font-size:14px;
  font-weight:700;
  cursor:pointer;
  transition:transform .18s ease,border-color .18s ease,background .18s ease,color .18s ease,box-shadow .18s ease;
}

.offset-chip:hover:not(:disabled),
.offset-chip:focus-visible{
  border-color:rgba(95,216,255,.34);
  transform:translateY(-1px);
}

.offset-chip:focus-visible{
  outline:none;
  box-shadow:0 0 0 2px rgba(95,216,255,.18);
}

.offset-chip.active{
  background:linear-gradient(180deg,rgba(227,25,55,.88) 0%,rgba(162,14,37,.96) 100%);
  border-color:rgba(255,123,146,.48);
  color:#fff;
  box-shadow:0 14px 28px rgba(104,9,28,.26);
}

.offset-chip:disabled{
  opacity:.42;
  cursor:not-allowed;
  transform:none;
}

.row,
.status-row{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  padding:12px 0;
  border-bottom:1px solid rgba(148,163,184,.14);
}

.row:last-child,
.status-row:last-child{
  border-bottom:none;
}

.row-compact{
  padding-top:0;
}

.row-label{
  font-size:14px;
  font-weight:600;
  min-width:0;
  flex:1;
}

.toggle{
  position:relative;
  width:52px;
  height:30px;
  flex:0 0 auto;
}

.toggle input{
  opacity:0;
  width:0;
  height:0;
}

.slider{
  position:absolute;
  inset:0;
  background:#30415e;
  border-radius:999px;
  cursor:pointer;
  transition:background .2s ease;
}

.slider:before{
  content:"";
  position:absolute;
  left:4px;
  bottom:4px;
  width:22px;
  height:22px;
  border-radius:50%;
  background:#fff;
  transition:transform .2s ease;
}

input:checked+.slider{
  background:var(--green);
}

input:checked+.slider:before{
  transform:translateX(22px);
}

input:disabled+.slider{
  opacity:.45;
  cursor:not-allowed;
}

.field{
  padding:12px 0;
}

.field+.field{
  border-top:1px solid rgba(148,163,184,.14);
}

.field-label{
  display:block;
  margin-bottom:8px;
  font-size:11px;
  color:var(--muted);
}

.hero-field{
  padding-bottom:4px;
}

.hint{
  font-size:12px;
  line-height:1.55;
  color:var(--muted);
}

.hero-hint{
  margin-top:8px;
}

select,
.text-input,
.picker-trigger{
  width:100%;
  border-radius:14px;
  border:1px solid rgba(125,211,252,.14);
  background:#13213a;
  color:var(--text);
  padding:12px 14px;
  font-size:14px;
}

.text-input{
  appearance:none;
}

.text-area{
  min-height:118px;
  resize:vertical;
  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
}

.picker-wrap{
  width:100%;
  min-width:0;
}

.picker-native{
  display:none;
}

.picker-trigger{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  text-align:left;
  cursor:pointer;
  transition:transform .2s ease,border-color .2s ease,background .2s ease;
}

.picker-trigger:after{
  content:"";
  width:0;
  height:0;
  border-left:5px solid transparent;
  border-right:5px solid transparent;
  border-top:6px solid var(--muted);
  flex:0 0 auto;
}

.picker-trigger:disabled,
.save-btn:disabled,
.upload-btn:disabled,
.ghost-btn:disabled{
  opacity:.45;
  cursor:not-allowed;
  transform:none;
}

.secondary-btn,
.save-btn,
.upload-btn,
.ghost-btn{
  border-radius:14px;
  padding:11px 14px;
  font-size:14px;
  font-weight:700;
  cursor:pointer;
  transition:transform .2s ease,border-color .2s ease,background .2s ease;
}

.ghost-btn.small-btn{
  padding:8px 12px;
  font-size:12px;
  flex:0 0 auto;
}

.secondary-btn,
.ghost-btn{
  border:1px solid rgba(125,211,252,.16);
  background:rgba(19,33,58,.85);
  color:var(--text);
}

.save-btn,
.upload-btn{
  border:none;
  background:linear-gradient(180deg,var(--accent-strong) 0%,var(--accent) 100%);
  color:#fff;
}

.actions{
  display:flex;
  gap:10px;
  margin-top:14px;
}

.actions>button{
  flex:1;
}

.metrics-card{
  display:grid;
  grid-template-rows:auto minmax(0,1fr);
  gap:14px;
}

.metrics-head{
  display:flex;
  align-items:flex-end;
  justify-content:space-between;
  gap:12px;
}

.metrics-grid{
  min-height:0;
  display:grid;
  grid-template-columns:repeat(4,minmax(0,1fr));
  gap:10px;
  align-content:start;
}

.metric-panel{
  min-height:112px;
  padding:14px;
  border-radius:20px;
  background:var(--panel-soft);
  border:1px solid rgba(125,211,252,.12);
  display:flex;
  flex-direction:column;
  justify-content:space-between;
  gap:10px;
}

.metric-panel.primary{
  background:
    linear-gradient(180deg,rgba(95,216,255,.08) 0%,transparent 34%),
    linear-gradient(180deg,rgba(19,30,52,.94) 0%,rgba(12,18,33,.94) 100%);
}

.metric-panel.wide{
  grid-column:span 2;
  min-height:96px;
}

.metric-label{
  font-size:10px;
  color:var(--muted);
}

.metric-value{
  font-size:clamp(28px,3.4vw,40px);
  line-height:1;
  font-weight:800;
  letter-spacing:-1px;
}

.metric-time{
  font-size:clamp(22px,2.8vw,32px);
  letter-spacing:-.3px;
}

.green{color:var(--green)}
.amber{color:var(--amber)}

.metric-panel .status-text{
  max-width:none;
  text-align:left;
  word-break:break-word;
  font-size:22px;
  line-height:1.22;
  font-weight:800;
}

.metric-panel .status-wide{
  font-size:16px;
  font-weight:700;
}

.hero-mini-grid{
  display:grid;
  grid-template-columns:repeat(2,minmax(0,1fr));
  gap:10px;
}

.mini-stat{
  padding:14px;
  border-radius:18px;
  background:rgba(19,33,58,.72);
  border:1px solid rgba(125,211,252,.1);
}

.mini-stat-label{
  display:block;
  font-size:10px;
  color:var(--muted);
  margin-bottom:8px;
}

.mini-stat .status-text{
  max-width:none;
  text-align:left;
  font-size:16px;
  line-height:1.35;
}

.live-strip{
  grid-column:1 / -1;
  display:grid;
  grid-template-columns:repeat(8,minmax(0,1fr));
  gap:10px;
}

.live-item{
  min-height:84px;
  border-radius:20px;
  padding:12px 14px;
  display:flex;
  flex-direction:column;
  justify-content:space-between;
  gap:8px;
}

.live-label{
  font-size:10px;
  color:var(--muted);
}

.status-text{
  max-width:65%;
  text-align:right;
  word-break:break-word;
  font-size:14px;
  font-weight:700;
}

.live-item .status-text{
  max-width:none;
  text-align:left;
  font-size:15px;
  line-height:1.35;
}

.live-item.compact .status-text{
  font-size:22px;
  line-height:1;
}

.status-wide{max-width:none}
.status-ok{color:var(--green)}
.status-err{color:var(--red)}
.status-warn{color:var(--amber)}
.status-yes{color:var(--green)}
.status-no{color:#8195b1}

.msg{
  min-height:16px;
  margin-top:8px;
  text-align:center;
  font-size:12px;
}

.msg.ok{color:var(--green)}
.msg.err{color:var(--red)}

.inline-actions,
.section-head{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:10px;
}

.section-head{
  margin-top:14px;
}

.inline-actions .field-label,
.section-head .field-label{
  margin-bottom:0;
}

.saved-list{
  display:flex;
  flex-direction:column;
  gap:10px;
  margin-top:12px;
}

.saved-item{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  border-radius:16px;
  background:rgba(18,29,51,.78);
  border:1px solid rgba(125,211,252,.1);
  padding:12px 14px;
}

.saved-main{
  min-width:0;
  flex:1;
}

.saved-name{
  font-size:14px;
  font-weight:700;
  word-break:break-word;
}

.saved-tags{
  display:flex;
  flex-wrap:wrap;
  gap:6px;
  margin-top:8px;
}

.tag{
  display:inline-flex;
  align-items:center;
  padding:4px 8px;
  border-radius:999px;
  background:#26344c;
  color:var(--muted);
  font-size:11px;
  line-height:1;
}

.tag.ok{background:rgba(34,197,94,.16);color:#98f5b9}
.tag.busy{background:rgba(95,216,255,.16);color:#a9ecff}
.tag.warn{background:rgba(245,158,11,.16);color:#fbd38d}

.empty-box{
  border:1px dashed rgba(125,211,252,.16);
  border-radius:16px;
  padding:16px;
  text-align:center;
  font-size:12px;
  color:var(--muted);
}

.ota-row{
  display:flex;
  align-items:center;
  gap:10px;
  flex-wrap:wrap;
}

.file-btn{
  display:inline-flex;
  align-items:center;
  justify-content:center;
  border-radius:14px;
  border:1px solid rgba(125,211,252,.16);
  background:rgba(19,33,58,.85);
  color:var(--text);
  padding:10px 14px;
  font-size:13px;
  font-weight:700;
  cursor:pointer;
  transition:transform .2s ease,border-color .2s ease;
}

.file-name{
  min-width:0;
  font-size:12px;
  color:var(--muted);
  word-break:break-word;
  flex:1;
}

.progress{
  width:100%;
  height:6px;
  margin-top:12px;
  display:none;
  border-radius:999px;
  background:rgba(19,33,58,.92);
  overflow:hidden;
}

.progress-bar{
  width:0%;
  height:100%;
  background:linear-gradient(90deg,var(--green) 0%,#7df3a7 100%);
  transition:width .3s ease;
}

.dialog-modal{
  position:fixed;
  inset:0;
  display:none;
  align-items:center;
  justify-content:center;
  padding:16px;
  background:rgba(3,8,18,.76);
  backdrop-filter:blur(8px);
  z-index:9000;
}

.dialog-modal.open{
  display:flex;
}

.dialog-sheet{
  width:min(1120px,100%);
  max-height:min(92svh,900px);
  border-radius:28px;
  overflow:hidden;
  display:grid;
  grid-template-rows:auto minmax(0,1fr);
}

.dialog-sheet.narrow{
  width:min(780px,100%);
}

.dialog-head{
  display:flex;
  align-items:flex-start;
  justify-content:space-between;
  gap:16px;
  padding:18px 20px;
  border-bottom:1px solid rgba(125,211,252,.12);
  background:rgba(11,19,35,.96);
}

.dialog-title-wrap h3{
  font-size:24px;
  font-weight:800;
}

.dialog-title-wrap p{
  margin-top:8px;
  font-size:13px;
  line-height:1.6;
  color:var(--muted);
}

.dialog-close{
  border:none;
  background:rgba(19,33,58,.9);
  color:var(--muted);
  width:40px;
  height:40px;
  border-radius:12px;
  font-size:24px;
  line-height:1;
  cursor:pointer;
  transition:border-color .2s ease,transform .2s ease,background .2s ease;
  border:1px solid rgba(125,211,252,.14);
}

.dialog-body{
  min-height:0;
  overflow:auto;
  padding:18px;
  display:grid;
  gap:16px;
  background:linear-gradient(180deg,rgba(7,12,22,.98) 0%,rgba(6,10,18,.98) 100%);
}

.dialog-grid{
  grid-template-columns:repeat(2,minmax(0,1fr));
}

.dialog-card{
  border-radius:22px;
  padding:18px;
  background:rgba(18,29,51,.74);
  border:1px solid rgba(125,211,252,.1);
}

.dialog-card.full{
  grid-column:1 / -1;
}

.status-grid{
  display:grid;
  grid-template-columns:repeat(2,minmax(0,1fr));
  gap:0 16px;
}

.picker-modal{
  position:fixed;
  inset:0;
  display:none;
  align-items:flex-end;
  justify-content:center;
  padding:16px;
  background:rgba(2,8,23,.76);
  z-index:9999;
}

.picker-modal.open{
  display:flex;
}

.picker-sheet{
  width:min(560px,100%);
  max-height:min(80svh,640px);
  border-radius:22px;
  overflow:hidden;
}

.picker-head{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  padding:16px 18px;
  border-bottom:1px solid rgba(125,211,252,.12);
}

.picker-title{
  font-size:15px;
  font-weight:700;
}

.picker-close{
  border:none;
  background:transparent;
  color:var(--muted);
  font-size:22px;
  line-height:1;
  cursor:pointer;
}

.picker-body{
  max-height:min(60svh,520px);
  overflow:auto;
  padding:10px;
}

.picker-option{
  width:100%;
  border:none;
  border-radius:14px;
  background:#172339;
  color:var(--text);
  padding:14px 16px;
  font-size:15px;
  text-align:left;
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  cursor:pointer;
}

.picker-option+.picker-option{
  margin-top:8px;
}

.picker-option.active{
  background:rgba(95,216,255,.16);
  color:var(--cyan);
}

.picker-option:after{
  content:"";
  width:10px;
  height:10px;
  border-radius:50%;
  border:2px solid currentColor;
  opacity:.3;
}

.picker-option.active:after{
  opacity:1;
  background:currentColor;
}

@media (max-width:1180px){
  body{padding:10px}
  .page{
    height:calc(100svh - 20px);
    min-height:calc(100vh - 20px);
  }
  .toolbar{
    width:min(720px,100%);
  }
  .dashboard-main{
    gap:12px;
  }
  .live-strip{
    grid-template-columns:repeat(4,minmax(0,1fr));
  }
}

@media (max-width:980px){
  .topbar{
    flex-direction:column;
  }
  .toolbar{
    width:100%;
    grid-template-columns:repeat(4,minmax(0,1fr));
  }
  .brand-block,
  .hero-card,
  .dialog-card{
    padding:16px;
  }
  .brand-block,
  .hero-card,
  .dialog-sheet,
  .picker-sheet{
    border-radius:24px;
  }
  .dashboard-main{
    grid-template-columns:minmax(252px,.88fr) minmax(0,1.12fr);
  }
  .metrics-head{
    align-items:flex-start;
  }
  .metric-panel{
    min-height:102px;
  }
  .metric-panel.wide{
    min-height:90px;
  }
  .live-item{
    min-height:78px;
  }
  .offset-grid{
    grid-template-columns:repeat(5,minmax(0,1fr));
  }
}

@media (max-width:760px){
  .brand-kicker,
  .section-tag,
  .metric-label,
  .live-label,
  .mini-stat-label,
  .field-label{
    letter-spacing:1.2px;
  }
  h1{
    font-size:clamp(26px,5.4vw,34px);
  }
  .page-subtitle,
  .speed-card-head p,
  .metrics-head p{
    display:none;
  }
  .dashboard-main{
    grid-template-columns:minmax(224px,.86fr) minmax(0,1.14fr);
  }
  .speed-card-head h2,
  .metrics-head h2{
    font-size:clamp(24px,4.6vw,30px);
  }
  .speed-quick{
    padding:14px 14px 16px;
  }
  .speed-quick-value{
    font-size:clamp(36px,6vw,48px);
  }
  .metric-value{
    font-size:clamp(24px,4.8vw,32px);
  }
  .metric-time{
    font-size:clamp(20px,4vw,28px);
  }
  .metric-panel .status-text{
    font-size:18px;
  }
  .metric-panel .status-wide{
    font-size:14px;
  }
  .status-text{
    max-width:none;
  }
}

/* Phone-sized H5 viewports switch to a readable scroll layout instead of clipping content. */
@media (max-width:640px), (max-width:920px) and (max-height:720px){
  html,
  body{
    height:auto;
  }
  body{
    min-height:100svh;
    overflow-x:hidden;
    overflow-y:auto;
    padding:8px;
  }
  .page{
    width:100%;
    height:auto;
    min-height:calc(100svh - 16px);
  }
  .app-shell{
    grid-template-rows:auto;
    align-content:start;
    gap:12px;
  }
  .topbar{
    flex-direction:column;
    gap:10px;
  }
  .toolbar{
    width:100%;
    grid-template-columns:repeat(2,minmax(0,1fr));
    gap:8px;
  }
  .toolbar-btn{
    min-height:92px;
  }
  .toolbar-meta{
    white-space:normal;
  }
  .dashboard-main{
    grid-template-columns:1fr;
    grid-template-rows:none;
    gap:12px;
  }
  .metrics-grid,
  .live-strip,
  .dialog-grid,
  .status-grid{
    grid-template-columns:repeat(2,minmax(0,1fr));
  }
  .metric-panel.wide{
    grid-column:span 2;
  }
  .metric-panel,
  .live-item,
  .mini-stat{
    min-height:auto;
  }
  .dialog-modal,
  .picker-modal{
    padding:10px;
  }
  .dialog-sheet,
  .dialog-sheet.narrow{
    width:min(920px,100%);
  }
  .dialog-body{
    padding:14px;
  }
  .page-subtitle,
  .speed-card-head p,
  .metrics-head p,
  .dialog-title-wrap p{
    display:block;
    font-size:12px;
    line-height:1.5;
  }
  .offset-grid{
    grid-template-columns:repeat(4,minmax(0,1fr));
  }
  .offset-chip{
    min-height:42px;
    font-size:14px;
  }
}

@media (max-width:420px){
  .metrics-grid,
  .live-strip,
  .dialog-grid,
  .status-grid{
    grid-template-columns:1fr;
  }
  .metric-panel.wide{
    grid-column:auto;
  }
  .offset-grid{
    grid-template-columns:repeat(2,minmax(0,1fr));
  }
  .speed-quick-value{
    font-size:clamp(34px,13vw,42px);
  }
  .metric-value{
    font-size:clamp(22px,10vw,30px);
  }
  .metric-panel .status-text{
    font-size:17px;
  }
  .live-item.compact .status-text{
    font-size:20px;
  }
}

@media (max-width:320px){
  .toolbar{
    grid-template-columns:1fr;
  }
  .actions,
  .inline-actions,
  .section-head,
  .saved-item,
  .dialog-head,
  .ota-row{
    flex-direction:column;
    align-items:flex-start;
  }
  .dialog-close{
    align-self:flex-end;
  }
  .offset-grid{
    grid-template-columns:1fr;
  }
}

@media (max-height:820px) and (min-width:641px){
  .page{height:calc(100svh - 18px)}
  .app-shell{gap:10px}
  .brand-block{padding:16px 20px}
  .hero-card{padding:16px}
  .speed-card{gap:12px}
  .metric-panel{min-height:94px}
  .metric-panel.wide{min-height:86px}
  .live-item{min-height:72px}
  .speed-quick-value{font-size:48px}
  .speed-card-head p,
  .metrics-head p,
  .page-subtitle{font-size:12px}
}

@media (prefers-reduced-motion:reduce){
  *,
  *:before,
  *:after{
    animation:none !important;
    transition:none !important;
    scroll-behavior:auto !important;
  }
}
</style>
  </head>
  <body>
    <div class="page app-shell">
      <header class="topbar">
        <div class="brand-block">
          <div class="brand-kicker">TESLA FSD WIFI CONTROLLER</div>
          <h1>FSD 控制器</h1>
        </div>
        <div class="toolbar">
          <button
            type="button"
            class="toolbar-btn"
            onclick="openDialog('fsdModal')"
          >
            <span class="toolbar-label">FSD 设置</span>
            <span class="toolbar-meta" id="toolbarFsdMeta">硬件 --</span>
          </button>
          <button
            type="button"
            class="toolbar-btn"
            onclick="openDialog('dnsModal')"
          >
            <span class="toolbar-label">白名单过滤</span>
            <span class="toolbar-meta" id="toolbarDnsMeta">规则 --</span>
          </button>
          <button
            type="button"
            class="toolbar-btn"
            onclick="openDialog('networkModal')"
          >
            <span class="toolbar-label">网络热点</span>
            <span class="toolbar-meta" id="toolbarNetworkMeta">上游 --</span>
          </button>
          <button
            type="button"
            class="toolbar-btn"
            onclick="openDialog('otaModal')"
          >
            <span class="toolbar-label">固件升级</span>
            <span class="toolbar-meta">上传 .bin</span>
          </button>
        </div>
      </header>

      <main class="dashboard-main">
        <section class="hero-card speed-card">
          <div class="section-tag">首屏控制</div>
          <div class="speed-card-head">
            <div>
              <h2>HW3 速度偏移</h2>
            </div>
            <div class="hardware-pill" id="hwModeBadge">硬件 --</div>
          </div>

          <div class="speed-hero">
            <div class="speed-quick">
              <div class="speed-quick-label">当前偏移</div>
              <div class="speed-quick-value" id="speedOffsetDisplay">+0%</div>
              <div class="speed-quick-note" id="speedOffsetState">读取中</div>
            </div>
          </div>

          <div class="hero-controls">
            <div class="row row-compact">
              <span class="row-label">启用速度偏移</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="speedOffsetEnable"
                  onchange="setVal('speedOffsetEnable',this.checked?1:0)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
            <div class="field hero-field">
              <label class="field-label" for="speedOffsetPct">偏移百分比</label>
              <div class="speed-offset-panel">
                <select
                  id="speedOffsetPct"
                  class="picker-native"
                  onchange="setVal('speedOffsetPct',this.value)"
                >
                  <option value="0" selected>+0%</option>
                  <option value="5">+5%</option>
                  <option value="10">+10%</option>
                  <option value="15">+15%</option>
                  <option value="20">+20%</option>
                  <option value="25">+25%</option>
                  <option value="30">+30%</option>
                  <option value="35">+35%</option>
                  <option value="40">+40%</option>
                  <option value="45">+45%</option>
                  <option value="50">+50%</option>
                </select>
                <div
                  class="offset-grid"
                  id="speedOffsetOptions"
                  role="group"
                  aria-label="速度偏移百分比"
                >
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="0"
                    onclick="chooseSpeedOffsetPreset('0')"
                  >
                    +0%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="5"
                    onclick="chooseSpeedOffsetPreset('5')"
                  >
                    +5%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="10"
                    onclick="chooseSpeedOffsetPreset('10')"
                  >
                    +10%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="15"
                    onclick="chooseSpeedOffsetPreset('15')"
                  >
                    +15%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="20"
                    onclick="chooseSpeedOffsetPreset('20')"
                  >
                    +20%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="25"
                    onclick="chooseSpeedOffsetPreset('25')"
                  >
                    +25%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="30"
                    onclick="chooseSpeedOffsetPreset('30')"
                  >
                    +30%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="35"
                    onclick="chooseSpeedOffsetPreset('35')"
                  >
                    +35%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="40"
                    onclick="chooseSpeedOffsetPreset('40')"
                  >
                    +40%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="45"
                    onclick="chooseSpeedOffsetPreset('45')"
                  >
                    +45%
                  </button>
                  <button
                    type="button"
                    class="offset-chip"
                    data-value="50"
                    onclick="chooseSpeedOffsetPreset('50')"
                  >
                    +50%
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section class="hero-card metrics-card">
          <div class="metrics-head">
            <div>
              <div class="section-tag">实时指标</div>
              <h2>核心数据</h2>
            </div>
            <p>主要状态保持在首屏，一眼确认设备是否正常工作。</p>
          </div>

          <div class="metrics-grid">
            <article class="metric-panel primary">
              <span class="metric-label">已修改</span>
              <strong class="metric-value green" id="sModified">0</strong>
            </article>
            <article class="metric-panel primary">
              <span class="metric-label">已接收</span>
              <strong class="metric-value" id="sRX">0</strong>
            </article>
            <article class="metric-panel primary">
              <span class="metric-label">错误</span>
              <strong class="metric-value amber" id="sErrors">0</strong>
            </article>
            <article class="metric-panel primary">
              <span class="metric-label">运行时间</span>
              <strong class="metric-value metric-time" id="sUptime">0秒</strong>
            </article>
            <article class="metric-panel">
              <span class="metric-label">CAN 总线</span>
              <strong id="sCAN" class="status-no status-text">--</strong>
            </article>
            <article class="metric-panel">
              <span class="metric-label">FSD 触发</span>
              <strong id="sFSD" class="status-no status-text">--</strong>
            </article>
            <article class="metric-panel wide">
              <span class="metric-label">芯片温度</span>
              <strong id="sChipTemp" class="status-no status-text status-wide"
                >--</strong
              >
            </article>
            <article class="metric-panel wide">
              <span class="metric-label">温控状态</span>
              <strong id="sThermal" class="status-no status-text status-wide"
                >--</strong
              >
            </article>
          </div>
        </section>

        <section class="live-strip">
          <div class="live-item">
            <span class="live-label">上游状态</span>
            <span id="sUpstream" class="status-no status-text">--</span>
          </div>
          <div class="live-item">
            <span class="live-label">当前热点</span>
            <span
              id="sCurrentUpstream"
              class="status-no status-text status-wide"
              >--</span
            >
          </div>
          <div class="live-item">
            <span class="live-label">上游 RSSI</span>
            <span id="sUpstreamRSSI" class="status-no status-text">--</span>
          </div>
          <div class="live-item compact">
            <span class="live-label">AP 客户端</span>
            <span id="sAPClients" class="status-no status-text">0</span>
          </div>
          <div class="live-item">
            <span class="live-label">DNS 状态</span>
            <span id="sDNSMode" class="status-no status-text status-wide"
              >--</span
            >
          </div>
          <div class="live-item compact">
            <span class="live-label">白名单</span>
            <span id="sDNSCount" class="status-no status-text">0</span>
          </div>
          <div class="live-item compact">
            <span class="live-label">已拦截</span>
            <span id="sDNSBlocked" class="status-no status-text">0</span>
          </div>
          <div class="live-item">
            <span class="live-label">本地 AP</span>
            <span id="sAP" class="status-ok status-text">--</span>
          </div>
        </section>
      </main>
    </div>

    <div
      class="dialog-modal"
      id="fsdModal"
      onclick="closeDialog(event,'fsdModal')"
    >
      <div class="dialog-sheet narrow" onclick="event.stopPropagation()">
        <div class="dialog-head">
          <div class="dialog-title-wrap">
            <h3>FSD 设置</h3>
            <p>除了 HW3 速度偏移之外的控制项，都收进这里，避免首页被稀释。</p>
          </div>
          <button
            type="button"
            class="dialog-close"
            onclick="closeDialog(null,'fsdModal')"
          >
            &times;
          </button>
        </div>
        <div class="dialog-body">
          <div class="dialog-card">
            <div class="card-title">基础控制</div>
            <div class="row">
              <span class="row-label">FSD 开关</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="fsdEnable"
                  checked
                  onchange="setVal('fsdEnable',this.checked?1:0)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
            <div class="row">
              <span class="row-label">硬件版本</span>
              <div class="picker-wrap">
                <select
                  id="hwMode"
                  class="picker-native"
                  data-picker-title="硬件版本"
                  data-picker-trigger="hwModeBtn"
                  onchange="setVal('hwMode',this.value)"
                >
                  <option value="0">LEGACY</option>
                  <option value="1">HW3</option>
                  <option value="2" selected>HW4</option>
                </select>
                <button
                  type="button"
                  class="picker-trigger"
                  id="hwModeBtn"
                  onclick="openPicker('hwMode')"
                ></button>
              </div>
            </div>
            <div class="row">
              <span class="row-label">速度模式</span>
              <div class="picker-wrap">
                <select
                  id="speedProfile"
                  class="picker-native"
                  data-picker-title="速度模式"
                  data-picker-trigger="speedProfileBtn"
                  onchange="setVal('speedProfile',this.value)"
                >
                  <option value="0">保守</option>
                  <option value="1" selected>默认</option>
                  <option value="2">适中</option>
                  <option value="3">激进</option>
                  <option value="4">最大</option>
                </select>
                <button
                  type="button"
                  class="picker-trigger"
                  id="speedProfileBtn"
                  onclick="openPicker('speedProfile')"
                ></button>
              </div>
            </div>
            <div class="row">
              <span class="row-label">模式来源</span>
              <div class="picker-wrap">
                <select
                  id="profileMode"
                  class="picker-native"
                  data-picker-title="模式来源"
                  data-picker-trigger="profileModeBtn"
                  onchange="setVal('profileMode',this.value)"
                >
                  <option value="1" selected>自动（拨杆）</option>
                  <option value="0">手动</option>
                </select>
                <button
                  type="button"
                  class="picker-trigger"
                  id="profileModeBtn"
                  onclick="openPicker('profileMode')"
                ></button>
              </div>
            </div>
          </div>

          <div class="dialog-card">
            <div class="card-title">附加功能</div>
            <div class="row">
              <span class="row-label">限速提示音抑制</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="isaChime"
                  onchange="setVal('isaChime',this.checked?1:0)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
            <div class="row">
              <span class="row-label">紧急车辆检测</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="emergencyDet"
                  checked
                  onchange="setVal('emergencyDet',this.checked?1:0)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
            <div class="row">
              <span class="row-label">中国模式</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="chinaMode"
                  onchange="setVal('chinaMode',this.checked?1:0)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div
      class="dialog-modal"
      id="dnsModal"
      onclick="closeDialog(event,'dnsModal')"
    >
      <div class="dialog-sheet" onclick="event.stopPropagation()">
        <div class="dialog-head">
          <div class="dialog-title-wrap">
            <h3>白名单过滤</h3>
            <p>
              白名单、黑名单与最近被拦截请求都收进这个弹窗，首页只保留结果状态。
            </p>
          </div>
          <button
            type="button"
            class="dialog-close"
            onclick="closeDialog(null,'dnsModal')"
          >
            &times;
          </button>
        </div>
        <div class="dialog-body dialog-grid">
          <div class="dialog-card">
            <div class="card-title">规则控制</div>
            <div class="row">
              <span class="row-label">启用 DNS 规则</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="dnsWhitelistEnable"
                  onchange="markDnsDirty()" /><span class="slider"></span
              ></label>
            </div>
            <div class="field">
              <label class="field-label" for="dnsAllowlist"
                >允许解析的域名</label
              >
              <textarea
                class="text-input text-area"
                id="dnsAllowlist"
                maxlength="384"
                placeholder="每行一个域名，例如：&#10;tesla.com&#10;apple.com"
                oninput="markDnsDirty()"
              ></textarea>
            </div>
            <div class="field">
              <label class="field-label" for="dnsBlocklist"
                >禁止解析的域名</label
              >
              <textarea
                class="text-input text-area"
                id="dnsBlocklist"
                maxlength="384"
                placeholder="每行一个域名，例如：&#10;google.com&#10;doubleclick.net"
                oninput="markDnsDirty()"
              ></textarea>
            </div>
            <div class="hint">
              支持逗号、空格或换行分隔。填写 `tesla.com` 会同时允许
              `api.tesla.com` 这类子域名。
            </div>
            <div class="hint">
              黑名单优先于白名单。若白名单留空，则表示“除黑名单外全部放行”；白名单非空时，只允许解析白名单域名。
            </div>
            <div class="actions">
              <button class="save-btn" onclick="saveDns()">
                保存 DNS 规则
              </button>
            </div>
            <div class="msg" id="dnsMsg"></div>
          </div>

          <div class="dialog-card">
            <div class="card-title">过滤状态</div>
            <div class="status-row">
              <span>黑名单数量</span
              ><span id="sDNSBlockCount" class="status-no status-text">0</span>
            </div>
            <div class="hint">
              首页会实时显示 DNS
              总状态、白名单条数和拦截总数，这里只看详细记录。
            </div>
            <div class="section-head">
              <div class="field-label">最近被拦截请求</div>
              <button class="ghost-btn small-btn" onclick="clearBlockedDns()">
                清空记录
              </button>
            </div>
            <div class="hint">按域名聚合统计被拦截次数，设备重启后会清空。</div>
            <div class="saved-list" id="dnsBlockedList"></div>
          </div>
        </div>
      </div>
    </div>

    <div
      class="dialog-modal"
      id="networkModal"
      onclick="closeDialog(event,'networkModal')"
    >
      <div class="dialog-sheet" onclick="event.stopPropagation()">
        <div class="dialog-head">
          <div class="dialog-title-wrap">
            <h3>网络热点</h3>
            <p>
              本地 AP、上游热点与 NAT 明细放在这里，首页仅保留连接状态摘要。
            </p>
          </div>
          <button
            type="button"
            class="dialog-close"
            onclick="closeDialog(null,'networkModal')"
          >
            &times;
          </button>
        </div>
        <div class="dialog-body dialog-grid">
          <div class="dialog-card">
            <div class="card-title">本地热点</div>
            <div class="field">
              <label class="field-label" for="apSSID">本地热点名称</label>
              <input
                class="text-input"
                type="text"
                id="apSSID"
                maxlength="32"
                placeholder="例如：FSD-Controller"
                oninput="markApDirty()"
              />
            </div>
            <div class="field">
              <label class="field-label" for="apPass">本地热点密码</label>
              <input
                class="text-input"
                type="password"
                id="apPass"
                maxlength="63"
                placeholder="8-63 个字符"
                oninput="markApDirty()"
              />
            </div>
            <div class="actions">
              <button class="save-btn" onclick="saveApConfig()">
                保存本地热点
              </button>
            </div>
            <div class="msg" id="apMsg"></div>
            <div class="hint">
              保存后设备会重启本地
              AP，当前连接会断开，请重新连接新的热点名称和密码。
            </div>
            <div class="status-row">
              <span>AP 地址</span
              ><span id="sAPIP" class="status-ok status-text">--</span>
            </div>
          </div>

          <div class="dialog-card">
            <div class="card-title">上游热点</div>
            <div class="row">
              <span class="row-label">启用手机热点接入</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="upstreamEnable"
                  onchange="setUpstreamEnabled(this.checked)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
            <div class="field">
              <div class="inline-actions">
                <label class="field-label" for="scanResults"
                  >搜索附近热点</label
                >
                <button
                  class="ghost-btn small-btn"
                  id="scanBtn"
                  onclick="scanUpstreamNetworks()"
                >
                  搜索热点
                </button>
              </div>
              <div class="picker-wrap">
                <select
                  id="scanResults"
                  class="picker-native"
                  data-picker-title="选择附近热点"
                  data-picker-trigger="scanResultsBtn"
                >
                  <option value="">点击“搜索热点”查看附近可用热点</option>
                </select>
                <button
                  type="button"
                  class="picker-trigger"
                  id="scanResultsBtn"
                  onclick="openPicker('scanResults')"
                ></button>
              </div>
            </div>
            <div class="field">
              <label class="field-label" for="upstreamPass">热点密码</label>
              <input
                class="text-input"
                type="password"
                id="upstreamPass"
                maxlength="63"
                placeholder="首次添加或更新密码时填写"
              />
            </div>
            <div class="actions">
              <button class="save-btn" onclick="saveSelectedUpstream()">
                保存选中热点
              </button>
            </div>
            <div class="msg" id="netMsg"></div>
            <div class="hint">
              支持保存多个热点，设备会自动跳过本机发射的
              AP，并优先尝试当前能连上的热点。
            </div>
            <div class="saved-list" id="savedNetworks"></div>
          </div>

          <div class="dialog-card full">
            <div class="card-title">网络状态细节</div>
            <div class="status-grid">
              <div class="status-row">
                <span>已保存热点</span
                ><span id="sSavedUpstreams" class="status-no status-text"
                  >0</span
                >
              </div>
              <div class="status-row">
                <span>信号质量</span
                ><span id="sUpstreamSignal" class="status-no status-text"
                  >--</span
                >
              </div>
              <div class="status-row">
                <span>当前信道</span
                ><span id="sWiFiChannel" class="status-no status-text">--</span>
              </div>
              <div class="status-row">
                <span>上游 IP</span
                ><span id="sUpstreamIP" class="status-no status-text">--</span>
              </div>
              <div class="status-row">
                <span>NAT 转发</span
                ><span id="sNAT" class="status-no status-text">--</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div
      class="dialog-modal"
      id="otaModal"
      onclick="closeDialog(event,'otaModal')"
    >
      <div class="dialog-sheet narrow" onclick="event.stopPropagation()">
        <div class="dialog-head">
          <div class="dialog-title-wrap">
            <h3>固件升级</h3>
            <p>升级入口保留，但不再占用首页面积。</p>
          </div>
          <button
            type="button"
            class="dialog-close"
            onclick="closeDialog(null,'otaModal')"
          >
            &times;
          </button>
        </div>
        <div class="dialog-body">
          <div class="dialog-card">
            <div class="card-title">OTA 更新</div>
            <div class="ota-row">
              <label class="file-btn" for="fwFile">选择文件</label>
              <input
                type="file"
                id="fwFile"
                accept=".bin"
                style="display: none"
                onchange="fileChosen(this)"
              />
              <span class="file-name" id="fileName">未选择文件</span>
            </div>
            <button
              class="upload-btn"
              id="uploadBtn"
              disabled
              onclick="doOTA()"
            >
              上传固件
            </button>
            <div class="progress" id="progWrap">
              <div class="progress-bar" id="progBar"></div>
            </div>
            <div class="msg" id="otaMsg"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="picker-modal" id="pickerModal" onclick="closePicker(event)">
      <div class="picker-sheet" onclick="event.stopPropagation()">
        <div class="picker-head">
          <div class="picker-title" id="pickerTitle">请选择</div>
          <button type="button" class="picker-close" onclick="closePicker()">
            &times;
          </button>
        </div>
        <div class="picker-body" id="pickerBody"></div>
      </div>
    </div>

    <script>
let dnsDirty=false;
let apDirty=false;
let scanResults=[];
let pendingScanResultsRender=false;
let latestBlockedDnsRequests=[];
let latestStatusUptime=0;
let activePickerId='';
const hwModeLabels={
  '0':'LEGACY',
  '1':'HW3',
  '2':'HW4'
};

function setTextIfPresent(id,text){
  const el=document.getElementById(id);
  if(el)el.textContent=text;
}

function markDnsDirty(){
  dnsDirty=true;
  renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
  syncDashboardSummary();
}

function markApDirty(){
  apDirty=true;
}

function setStatusText(id,text,className){
  const el=document.getElementById(id);
  if(!el)return;
  el.textContent=text;
  el.className=className+' status-text';
}

function setWideStatusText(id,text,className){
  const el=document.getElementById(id);
  if(!el)return;
  el.textContent=text;
  el.className=className+' status-text status-wide';
}

function formatChipTemp(current,average){
  const currentValid=typeof current==='number'&&Number.isFinite(current);
  const avgValid=typeof average==='number'&&Number.isFinite(average);
  if(!currentValid&&!avgValid)return '--';
  if(currentValid&&avgValid)return current.toFixed(1)+'°C / 平均 '+average.toFixed(1)+'°C';
  if(currentValid)return current.toFixed(1)+'°C';
  return '平均 '+average.toFixed(1)+'°C';
}

function getSignalClass(rssi){
  if(typeof rssi!=='number'||!Number.isFinite(rssi))return 'status-no';
  if(rssi>=-55)return 'status-ok';
  if(rssi>=-67)return 'status-ok';
  if(rssi>=-75)return 'status-warn';
  return 'status-err';
}

function getHwModeLabel(value){
  return hwModeLabels[String(value)]||'--';
}

function syncDashboardSummary(data){
  const hwSelect=document.getElementById('hwMode');
  const offsetSelect=document.getElementById('speedOffsetPct');
  const offsetToggle=document.getElementById('speedOffsetEnable');
  const fsdToggle=document.getElementById('fsdEnable');
  const dnsToggle=document.getElementById('dnsWhitelistEnable');
  const currentUpstream=document.getElementById('sCurrentUpstream');
  const upstreamStatus=document.getElementById('sUpstream');
  const hwLabel=data?getHwModeLabel(data.hwMode):getSelectDisplayText(hwSelect);
  const offsetLabel=data?('+'+String(Number(data.speedOffsetPct||0))+'%'):getSelectDisplayText(offsetSelect);
  const isHw3=data?String(data.hwMode)==='1':hwLabel==='HW3';
  const offsetEnabled=data?!!data.speedOffsetEnable:!!(offsetToggle&&offsetToggle.checked);
  const fsdEnabled=data?!!data.fsdEnable:!!(fsdToggle&&fsdToggle.checked);
  const dnsEnabled=data?!!data.dnsWhitelistEnable:!!(dnsToggle&&dnsToggle.checked);
  const dnsCount=data?Number(data.dnsWhitelistCount||0):getDnsRulesFromTextarea('dnsAllowlist').length;
  const currentUpstreamText=(data?(data.connectedUpstreamSSID||data.upstreamSSID||''):((currentUpstream&&currentUpstream.textContent)||'')).trim();
  const upstreamStatusText=(data?(data.upstreamStatus||'--'):((upstreamStatus&&upstreamStatus.textContent)||'--')).trim();
  let offsetState='已关闭';
  if(!isHw3)offsetState='当前为 '+hwLabel+'，仅 HW3 可用';
  else if(offsetEnabled)offsetState='已启用，按当前限速上浮';

  setTextIfPresent('hwModeBadge','硬件 '+hwLabel);
  setTextIfPresent('speedOffsetDisplay',offsetLabel);
  setTextIfPresent('speedOffsetState',offsetState);
  setTextIfPresent('toolbarFsdMeta','硬件 '+hwLabel+' · '+(fsdEnabled?'已启用':'已关闭'));
  setTextIfPresent('toolbarDnsMeta',(dnsEnabled?'已启用':'未启用')+' · 白名单 '+dnsCount+' 条');
  setTextIfPresent('toolbarNetworkMeta',currentUpstreamText&&currentUpstreamText!=='--'?currentUpstreamText:'上游 '+(upstreamStatusText||'--'));
}

function syncSpeedOffsetOptions(){
  const select=document.getElementById('speedOffsetPct');
  const wrap=document.getElementById('speedOffsetOptions');
  if(!select||!wrap)return;
  const buttons=wrap.querySelectorAll('.offset-chip');
  buttons.forEach(btn=>{
    const isActive=btn.dataset.value===String(select.value);
    btn.classList.toggle('active',isActive);
    btn.disabled=!!select.disabled;
    btn.setAttribute('aria-pressed',isActive?'true':'false');
  });
}

function chooseSpeedOffsetPreset(value){
  const select=document.getElementById('speedOffsetPct');
  if(!select||select.disabled)return;
  select.value=String(value);
  select.dispatchEvent(new Event('change',{bubbles:true}));
  syncSpeedOffsetOptions();
  syncDashboardSummary();
}

function openDialog(id){
  const dialog=document.getElementById(id);
  if(dialog)dialog.classList.add('open');
}

function closeDialog(evt,id){
  const dialog=id?document.getElementById(id):(evt&&evt.target&&evt.target.classList.contains('dialog-modal')?evt.target:null);
  if(!dialog)return;
  if(evt&&evt.target&&evt.target!==dialog)return;
  dialog.classList.remove('open');
}

function syncNetworkForm(d){
  if(!apDirty){
    document.getElementById('apSSID').value=d.apSSID||'';
    document.getElementById('apPass').value=d.apPassword||'';
  }
  document.getElementById('upstreamEnable').checked=!!d.upstreamEnable;
  const savedNetworks=Array.isArray(d.upstreamNetworks)?d.upstreamNetworks:[];
  let scanSavedStateChanged=false;
  scanResults.forEach(net=>{
    const nextSaved=savedNetworks.some(saved=>saved.ssid===net.ssid);
    if(net.saved!==nextSaved){
      net.saved=nextSaved;
      scanSavedStateChanged=true;
    }
  });
  if(scanSavedStateChanged){
    refreshScanResultsSelect();
  }
  renderSavedNetworks(savedNetworks);
}

function syncDnsForm(d){
  if(dnsDirty)return;
  document.getElementById('dnsWhitelistEnable').checked=!!d.dnsWhitelistEnable;
  document.getElementById('dnsAllowlist').value=d.dnsAllowlist||'';
  document.getElementById('dnsBlocklist').value=d.dnsBlocklist||'';
}

function setNetMessage(text,type){
  const msg=document.getElementById('netMsg');
  msg.textContent=text;
  msg.className='msg'+(type?' '+type:'');
}

function setApMessage(text,type){
  const msg=document.getElementById('apMsg');
  msg.textContent=text;
  msg.className='msg'+(type?' '+type:'');
}

function normalizeDomain(domain){
  let normalized=(domain||'').trim().toLowerCase();
  while(normalized.endsWith('.'))normalized=normalized.slice(0,-1);
  return normalized;
}

function getDnsRulesFromTextarea(id){
  return (document.getElementById(id).value||'')
    .split(/[\s,;]+/)
    .map(normalizeDomain)
    .filter(Boolean);
}

function ruleMatchesDomain(domain,rule){
  if(!domain||!rule)return false;
  return domain===rule||(domain.length>rule.length&&domain.endsWith('.'+rule));
}

function isDomainAlreadyAllowed(domain){
  const normalizedDomain=normalizeDomain(domain);
  if(!normalizedDomain)return false;
  return getDnsRulesFromTextarea('dnsAllowlist').some(rule=>ruleMatchesDomain(normalizedDomain,rule));
}

function isDomainBlockedByBlacklist(domain){
  const normalizedDomain=normalizeDomain(domain);
  if(!normalizedDomain)return false;
  return getDnsRulesFromTextarea('dnsBlocklist').some(rule=>ruleMatchesDomain(normalizedDomain,rule));
}

function renderScanResults(){
  const select=document.getElementById('scanResults');
  const current=select.value;
  select.innerHTML='';

  if(!scanResults.length){
    const opt=document.createElement('option');
    opt.value='';
    opt.textContent='点击“搜索热点”查看附近可用热点';
    select.appendChild(opt);
    syncPickerButton('scanResults');
    return;
  }

  const placeholder=document.createElement('option');
  placeholder.value='';
  placeholder.textContent='请选择要保存的热点';
  select.appendChild(placeholder);

  scanResults.forEach(net=>{
    const opt=document.createElement('option');
    opt.value=net.ssid;
    let label=net.ssid;
    if(typeof net.rssi==='number')label+=' · '+net.rssi+' dBm';
    if(net.saved)label+=' · 已保存';
    opt.textContent=label;
    select.appendChild(opt);
  });

  if(scanResults.some(net=>net.ssid===current)){
    select.value=current;
  }
  syncPickerButton('scanResults');
}

function refreshScanResultsSelect(force){
  const select=document.getElementById('scanResults');
  if(!force&&document.activeElement===select){
    pendingScanResultsRender=true;
    return;
  }
  pendingScanResultsRender=false;
  renderScanResults();
}

function appendTag(parent,text,className){
  const tag=document.createElement('span');
  tag.className='tag'+(className?' '+className:'');
  tag.textContent=text;
  parent.appendChild(tag);
}

function renderSavedNetworks(networks){
  const wrap=document.getElementById('savedNetworks');
  wrap.innerHTML='';

  if(!Array.isArray(networks)||!networks.length){
    const empty=document.createElement('div');
    empty.className='empty-box';
    empty.textContent='还没有保存热点。先搜索附近热点，再保存需要自动连接的候选热点。';
    wrap.appendChild(empty);
    return;
  }

  networks.forEach(net=>{
    const item=document.createElement('div');
    item.className='saved-item';

    const main=document.createElement('div');
    main.className='saved-main';

    const name=document.createElement('div');
    name.className='saved-name';
    name.textContent=net.ssid;
    main.appendChild(name);

    const tags=document.createElement('div');
    tags.className='saved-tags';
    if(net.connected)appendTag(tags,'已连接','ok');
    else if(net.active)appendTag(tags,'连接中','busy');
    else appendTag(tags,'已保存','');
    if(!net.hasPass)appendTag(tags,'无密码','warn');
    main.appendChild(tags);

    const delBtn=document.createElement('button');
    delBtn.className='ghost-btn small-btn';
    delBtn.textContent='删除';
    delBtn.onclick=()=>deleteSavedUpstream(net.ssid);

    item.appendChild(main);
    item.appendChild(delBtn);
    wrap.appendChild(item);
  });
}

function formatRelativeTime(seconds){
  const delta=Math.max(0,seconds||0);
  if(delta<60)return delta+'秒前';
  if(delta<3600)return Math.floor(delta/60)+'分前';
  if(delta<86400)return Math.floor(delta/3600)+'小时前';
  return Math.floor(delta/86400)+'天前';
}

function renderBlockedDnsRequests(requests,currentUptime){
  const wrap=document.getElementById('dnsBlockedList');
  wrap.innerHTML='';

  if(!Array.isArray(requests)||!requests.length){
    const empty=document.createElement('div');
    empty.className='empty-box';
    empty.textContent='暂时没有被拦截域名统计。';
    wrap.appendChild(empty);
    return;
  }

  requests.forEach(item=>{
    const row=document.createElement('div');
    row.className='saved-item';
    const normalizedDomain=normalizeDomain(item.domain);
    const blockedByBlacklist=isDomainBlockedByBlacklist(normalizedDomain);
    const alreadyAllowed=isDomainAlreadyAllowed(normalizedDomain);

    const main=document.createElement('div');
    main.className='saved-main';

    const name=document.createElement('div');
    name.className='saved-name';
    name.textContent=item.domain||'(未知域名)';
    main.appendChild(name);

    const tags=document.createElement('div');
    tags.className='saved-tags';
    appendTag(tags,String(item.count||0)+'次','warn');
    appendTag(tags,formatRelativeTime((currentUptime||0)-(item.lastBlockedAt||0)),'busy');
    main.appendChild(tags);

    const addBtn=document.createElement('button');
    addBtn.className='ghost-btn small-btn';
    addBtn.textContent=blockedByBlacklist?'已在黑名单':(alreadyAllowed?'已在白名单':'加入白名单');
    addBtn.disabled=blockedByBlacklist||alreadyAllowed||!normalizedDomain;
    addBtn.onclick=()=>addBlockedDomainToAllowlist(normalizedDomain);

    row.appendChild(main);
    row.appendChild(addBtn);
    wrap.appendChild(row);
  });
}

function poll(){
  fetch('/api/status').then(r=>r.json()).then(d=>{
    document.getElementById('sModified').textContent=d.modified;
    document.getElementById('sRX').textContent=d.rx;
    document.getElementById('sErrors').textContent=d.errors;
    let u=d.uptime;
    let h=Math.floor(u/3600),m=Math.floor((u%3600)/60),s=u%60;
    document.getElementById('sUptime').textContent=h>0?h+'时'+m+'分':m>0?m+'分'+s+'秒':s+'秒';

    let canEl=document.getElementById('sCAN');
    canEl.textContent=d.canOK?'正常':'异常';
    canEl.className=(d.canOK?'status-ok':'status-err')+' status-text';

    let fsdEl=document.getElementById('sFSD');
    fsdEl.textContent=d.fsdTriggered?'是':'否';
    fsdEl.className=(d.fsdTriggered?'status-yes':'status-no')+' status-text';

    let thermalClass='status-ok';
    if(d.thermalProtect)thermalClass='status-err';
    else if((d.thermalStatus||'').includes('降频')||(d.thermalStatus||'').includes('偏高'))thermalClass='status-warn';
    let signalClass=getSignalClass(d.upstreamRSSI);

    document.getElementById('fsdEnable').checked=!!d.fsdEnable;
    document.getElementById('hwMode').value=d.hwMode;
    document.getElementById('speedProfile').value=d.speedProfile;
    document.getElementById('profileMode').value=d.profileMode?'1':'0';
    document.getElementById('speedOffsetEnable').checked=!!d.speedOffsetEnable;
    document.getElementById('speedOffsetPct').value=String(d.speedOffsetPct||0);
    document.getElementById('isaChime').checked=!!d.isaChime;
    document.getElementById('emergencyDet').checked=!!d.emergencyDet;
    document.getElementById('chinaMode').checked=!!d.chinaMode;

    const isHw3=String(d.hwMode)==='1';
    document.getElementById('speedOffsetEnable').disabled=!isHw3;
    document.getElementById('speedOffsetPct').disabled=!isHw3||!d.speedOffsetEnable;
    syncSpeedOffsetOptions();
    syncPickerButton('hwMode');
    syncPickerButton('speedProfile');
    syncPickerButton('profileMode');
    syncPickerButton('scanResults');

    syncNetworkForm(d);
    syncDnsForm(d);
    setStatusText('sUpstream',d.upstreamStatus||'--',d.upstreamConnected?'status-ok':(d.upstreamEnable?'status-err':'status-no'));
    setWideStatusText('sCurrentUpstream',d.connectedUpstreamSSID||d.upstreamSSID||'--',d.upstreamConnected?'status-ok':'status-no');
    setStatusText('sSavedUpstreams',String(d.upstreamSavedCount||0),d.upstreamSavedCount?'status-ok':'status-no');
    setStatusText('sUpstreamRSSI',typeof d.upstreamRSSI==='number'&&Number.isFinite(d.upstreamRSSI)?String(d.upstreamRSSI)+' dBm':'--',signalClass);
    setStatusText('sUpstreamSignal',d.upstreamSignal||'--',signalClass);
    setStatusText('sWiFiChannel',d.wifiChannel?String(d.wifiChannel):'--',d.wifiChannel?'status-ok':'status-no');
    setStatusText('sAPClients',String(d.apClients||0),(d.apClients||0)>1?'status-warn':'status-ok');
    setStatusText('sUpstreamIP',d.upstreamIP||'--',d.upstreamConnected?'status-ok':'status-no');
    setStatusText('sNAT',d.natStatus||'--',d.natEnabled?'status-ok':(d.upstreamConnected?'status-err':'status-no'));
    setStatusText('sAP',d.apSSID||'--','status-ok');
    setStatusText('sAPIP',d.apIP||'--','status-ok');
    setWideStatusText('sDNSMode',d.dnsWhitelistEnable?'已启用':'未启用',d.dnsWhitelistEnable?'status-ok':'status-no');
    setStatusText('sDNSCount',String(d.dnsWhitelistCount||0),d.dnsWhitelistCount?'status-ok':'status-no');
    setStatusText('sDNSBlockCount',String(d.dnsBlacklistCount||0),d.dnsBlacklistCount?'status-err':'status-no');
    setStatusText('sDNSBlocked',String(d.dnsBlockedCount||0),d.dnsBlockedCount?'status-err':'status-no');
    setWideStatusText('sChipTemp',formatChipTemp(d.chipTempC,d.chipTempAvgC),thermalClass);
    setWideStatusText('sThermal',d.thermalStatus||'--',thermalClass);
    latestBlockedDnsRequests=Array.isArray(d.dnsBlockedRequests)?d.dnsBlockedRequests:[];
    latestStatusUptime=d.uptime||0;
    renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
    syncDashboardSummary(d);
  }).catch(()=>{});
}

function setVal(key,val){
  fetch('/api/set?'+key+'='+val).catch(()=>{});
  if(key==='speedOffsetEnable'||key==='hwMode'){
    const select=document.getElementById('speedOffsetPct');
    const hwSelect=document.getElementById('hwMode');
    const offsetToggle=document.getElementById('speedOffsetEnable');
    if(select&&hwSelect){
      const nextHwMode=key==='hwMode'?String(val):String(hwSelect.value);
      const nextOffsetEnabled=key==='speedOffsetEnable'?!!Number(val):!!(offsetToggle&&offsetToggle.checked);
      select.disabled=nextHwMode!=='1'||!nextOffsetEnabled;
      syncSpeedOffsetOptions();
    }
  }
  syncDashboardSummary();
}

function getSelectDisplayText(select){
  if(!select||!select.options.length)return '请选择';
  const option=select.options[select.selectedIndex>=0?select.selectedIndex:0];
  return option&&option.textContent?option.textContent:'请选择';
}

function syncPickerButton(selectId){
  const select=document.getElementById(selectId);
  if(!select)return;
  const btnId=select.dataset.pickerTrigger;
  if(!btnId)return;
  const btn=document.getElementById(btnId);
  if(!btn)return;
  btn.textContent=getSelectDisplayText(select);
  btn.disabled=!!select.disabled;
}

function openPicker(selectId){
  const select=document.getElementById(selectId);
  if(!select||select.disabled)return;
  activePickerId=selectId;
  document.getElementById('pickerTitle').textContent=select.dataset.pickerTitle||'请选择';
  const body=document.getElementById('pickerBody');
  body.innerHTML='';
  for(let i=0;i<select.options.length;i++){
    const option=select.options[i];
    if(option.disabled)continue;
    const btn=document.createElement('button');
    btn.type='button';
    btn.className='picker-option'+(option.value===select.value?' active':'');
    btn.textContent=option.textContent;
    btn.onclick=()=>choosePickerValue(selectId,option.value);
    body.appendChild(btn);
  }
  document.getElementById('pickerModal').classList.add('open');
}

function choosePickerValue(selectId,value){
  const select=document.getElementById(selectId);
  if(!select)return;
  select.value=value;
  syncPickerButton(selectId);
  select.dispatchEvent(new Event('change',{bubbles:true}));
  syncDashboardSummary();
  closePicker();
}

function closePicker(evt){
  if(evt&&evt.target&&evt.target!==document.getElementById('pickerModal'))return;
  activePickerId='';
  document.getElementById('pickerModal').classList.remove('open');
}

function setUpstreamEnabled(enabled){
  setNetMessage('保存中...','');
  fetch('/api/set?upstreamEnable='+(enabled?'1':'0')).then(r=>{
    if(!r.ok)throw new Error('save failed');
    return r.text();
  }).then(()=>{
    setNetMessage(enabled?'热点接入已启用':'热点接入已关闭','ok');
    poll();
  }).catch(()=>{
    setNetMessage('保存失败','err');
    poll();
  });
}

function saveApConfig(){
  const ssid=(document.getElementById('apSSID').value||'').trim();
  const pass=document.getElementById('apPass').value||'';
  if(!ssid){
    setApMessage('热点名称不能为空','err');
    return;
  }
  if(ssid.length>32){
    setApMessage('热点名称最多 32 个字符','err');
    return;
  }
  if(pass.length<8||pass.length>63){
    setApMessage('热点密码长度必须为 8-63 个字符','err');
    return;
  }
  const params=new URLSearchParams();
  params.set('apSSID',ssid);
  params.set('apPass',pass);
  setApMessage('保存中，热点将重新启动...','');
  fetch('/api/set?'+params.toString()).then(async r=>{
    if(!r.ok){
      const txt=await r.text();
      throw new Error(txt||'save failed');
    }
    return r.text();
  }).then(()=>{
    apDirty=false;
    setApMessage('本地热点设置已保存，约 1 秒后会切换到新的名称和密码','ok');
  }).catch(err=>{
    setApMessage(err.message||'保存失败','err');
  });
}

function scanUpstreamNetworks(){
  const btn=document.getElementById('scanBtn');
  btn.disabled=true;
  setNetMessage('搜索中...','');

  fetch('/api/upstream/scan').then(r=>{
    if(!r.ok){
      return r.text().then(t=>{throw new Error(t||'scan failed');});
    }
    return r.json();
  }).then(d=>{
    scanResults=Array.isArray(d.results)?d.results:[];
    refreshScanResultsSelect(true);
    setNetMessage(scanResults.length?'已更新附近热点':'没有搜索到可用热点','ok');
  }).catch(err=>{
    setNetMessage(err.message||'搜索失败','err');
  }).finally(()=>{
    btn.disabled=false;
  });
}

function saveSelectedUpstream(){
  const ssid=document.getElementById('scanResults').value;
  const pass=document.getElementById('upstreamPass').value;

  if(!ssid){
    setNetMessage('请先选择要保存的热点','err');
    return;
  }

  const params=new URLSearchParams();
  params.set('ssid',ssid);
  if(pass)params.set('pass',pass);

  setNetMessage('保存中...','');

  fetch('/api/upstream/add?'+params.toString()).then(r=>{
    if(!r.ok){
      return r.text().then(t=>{throw new Error(t||'save failed');});
    }
    return r.text();
  }).then(()=>{
    document.getElementById('upstreamPass').value='';
    setNetMessage(document.getElementById('upstreamEnable').checked?'热点已保存，设备会自动切换到可连接的热点':'热点已保存，启用后会自动连接','ok');
    poll();
  }).catch(err=>{
    setNetMessage(err.message||'保存失败','err');
  });
}

function deleteSavedUpstream(ssid){
  if(!window.confirm('确定删除这个已保存热点吗？'))return;

  setNetMessage('删除中...','');
  fetch('/api/upstream/delete?ssid='+encodeURIComponent(ssid)).then(r=>{
    if(!r.ok){
      return r.text().then(t=>{throw new Error(t||'delete failed');});
    }
    return r.text();
  }).then(()=>{
    setNetMessage('已删除热点','ok');
    poll();
  }).catch(err=>{
    setNetMessage(err.message||'删除失败','err');
  });
}

['hwMode','speedProfile','profileMode','scanResults'].forEach(syncPickerButton);
syncSpeedOffsetOptions();
syncDashboardSummary();

document.addEventListener('keydown',evt=>{
  if(evt.key!=='Escape')return;
  closePicker();
  document.querySelectorAll('.dialog-modal.open').forEach(dialog=>dialog.classList.remove('open'));
});

function persistDnsRules(successText){
  const msg=document.getElementById('dnsMsg');
  const params=new URLSearchParams();

  params.set('dnsWhitelistEnable',document.getElementById('dnsWhitelistEnable').checked?'1':'0');
  params.set('dnsAllowlist',document.getElementById('dnsAllowlist').value.trim());
  params.set('dnsBlocklist',document.getElementById('dnsBlocklist').value.trim());

  msg.textContent='保存中...';
  msg.className='msg';

  fetch('/api/set?'+params.toString()).then(r=>{
    if(!r.ok)throw new Error('save failed');
    return r.text();
  }).then(()=>{
    dnsDirty=false;
    msg.textContent=successText||'DNS 规则已保存';
    msg.className='msg ok';
    poll();
  }).catch(()=>{
    msg.textContent='保存失败';
    msg.className='msg err';
  });
}

function saveDns(){
  persistDnsRules('DNS 规则已保存');
}

function addBlockedDomainToAllowlist(domain){
  const normalizedDomain=normalizeDomain(domain);
  const msg=document.getElementById('dnsMsg');

  if(!normalizedDomain){
    msg.textContent='域名无效，无法加入白名单';
    msg.className='msg err';
    return;
  }

  if(isDomainAlreadyAllowed(normalizedDomain)){
    msg.textContent='这个域名已经在白名单里了';
    msg.className='msg ok';
    renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
    return;
  }

  if(isDomainBlockedByBlacklist(normalizedDomain)){
    msg.textContent='这个域名已在黑名单里，黑名单优先，请先移除黑名单规则';
    msg.className='msg err';
    renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
    return;
  }

  const textarea=document.getElementById('dnsAllowlist');
  const current=textarea.value.trim();
  textarea.value=current?current+'\n'+normalizedDomain:normalizedDomain;
  dnsDirty=true;
  renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
  persistDnsRules('已加入白名单: '+normalizedDomain);
}

function clearBlockedDns(){
  const msg=document.getElementById('dnsMsg');
  msg.textContent='清空中...';
  msg.className='msg';

  fetch('/api/dns/blocked/clear').then(r=>{
    if(!r.ok)throw new Error('clear failed');
    return r.text();
  }).then(()=>{
    msg.textContent='拦截记录已清空';
    msg.className='msg ok';
    poll();
  }).catch(()=>{
    msg.textContent='清空失败';
    msg.className='msg err';
  });
}

function fileChosen(inp){
  document.getElementById('fileName').textContent=inp.files[0]?inp.files[0].name:'未选择文件';
  document.getElementById('uploadBtn').disabled=!inp.files[0];
}

function doOTA(){
  let file=document.getElementById('fwFile').files[0];
  if(!file)return;
  let xhr=new XMLHttpRequest();
  let prog=document.getElementById('progWrap');
  let bar=document.getElementById('progBar');
  let msg=document.getElementById('otaMsg');
  prog.style.display='block';
  bar.style.width='0%';
  msg.textContent='';
  msg.className='msg';
  document.getElementById('uploadBtn').disabled=true;
  xhr.upload.addEventListener('progress',e=>{if(e.lengthComputable)bar.style.width=Math.round(e.loaded/e.total*100)+'%';});
  xhr.onload=function(){
    if(xhr.status===200){msg.textContent='上传成功，正在重启...';msg.className='msg ok';}
    else{msg.textContent='上传失败: '+xhr.statusText;msg.className='msg err';document.getElementById('uploadBtn').disabled=false;}
  };
  xhr.onerror=function(){msg.textContent='连接失败';msg.className='msg err';document.getElementById('uploadBtn').disabled=false;};
  let form=new FormData();
  form.append('firmware',file);
  xhr.open('POST','/api/ota');
  xhr.send(form);
}

setInterval(poll,1000);
poll();
</script>
  </body>
</html>
)rawliteral";
