#pragma once

// Auto-generated from ui/index.html + ui/styles.css + ui/app.js
// Do not edit this file manually. Run scripts/generate_web_ui_header.py instead.

const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!doctype html>
<html lang="zh">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,user-scalable=no"
    />
    <title>FSD 控制器</title>
    <style>
:root{
  --bg:#02050b;
  --bg-2:#07101d;
  --surface:rgba(8,16,30,.82);
  --surface-strong:rgba(12,23,42,.96);
  --surface-soft:rgba(16,31,55,.62);
  --line:rgba(125,211,252,.17);
  --line-strong:rgba(125,211,252,.34);
  --text:#f3f8ff;
  --muted:#8ea4c4;
  --muted-strong:#c5d3e8;
  --cyan:#5fd8ff;
  --cyan-soft:rgba(95,216,255,.16);
  --green:#22c55e;
  --amber:#f59e0b;
  --red:#ef4444;
  --tesla:#e31937;
  --shadow:0 24px 90px rgba(0,0,0,.42);
}

*{margin:0;padding:0;box-sizing:border-box}
html,body{min-height:100%}
body{
  font-family:"PingFang SC","Microsoft YaHei",-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  color:var(--text);
  background:
    linear-gradient(rgba(95,216,255,.035) 1px,transparent 1px),
    linear-gradient(90deg,rgba(95,216,255,.03) 1px,transparent 1px),
    radial-gradient(circle at 20% 12%,rgba(95,216,255,.16),transparent 34%),
    radial-gradient(circle at 86% 18%,rgba(227,25,55,.16),transparent 30%),
    linear-gradient(155deg,#02050b 0%,#07101d 52%,#030712 100%);
  background-size:42px 42px,42px 42px,auto,auto,auto;
  min-height:100svh;
  overflow:hidden;
  padding:14px;
}

button,
input,
select,
textarea{
  font:inherit;
}

button{
  touch-action:manipulation;
}

.page{
  width:min(1440px,100%);
  height:calc(100svh - 28px);
  min-height:680px;
  margin:0 auto;
}

.app-shell{
  display:grid;
  grid-template-rows:auto minmax(0,1fr);
  gap:12px;
}

.hud-topbar{
  min-height:52px;
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
}

.hud-identity{
  min-width:0;
  display:inline-flex;
  align-items:center;
  gap:10px;
  color:var(--muted-strong);
  font-size:13px;
  font-weight:700;
  letter-spacing:.2px;
}

.hud-name{
  color:var(--text);
  font-size:14px;
}

.hud-divider{
  width:1px;
  height:18px;
  background:var(--line);
}

.live-dot{
  width:8px;
  height:8px;
  border-radius:50%;
  background:var(--green);
  box-shadow:0 0 14px rgba(34,197,94,.8);
}

.hud-actions{
  position:relative;
  display:flex;
  align-items:center;
  gap:8px;
  z-index:20;
}

.hud-popover-wrap{
  position:relative;
}

.icon-btn{
  width:46px;
  height:46px;
  border:1px solid var(--line);
  border-radius:16px;
  display:inline-flex;
  align-items:center;
  justify-content:center;
  color:var(--muted-strong);
  background:rgba(8,16,30,.56);
  box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 12px 32px rgba(0,0,0,.22);
  cursor:pointer;
  transition:background .2s ease,border-color .2s ease,color .2s ease,transform .2s ease;
}

.icon-btn svg{
  width:22px;
  height:22px;
  fill:none;
  stroke:currentColor;
  stroke-width:2;
  stroke-linecap:round;
  stroke-linejoin:round;
}

.icon-btn:hover,
.icon-btn:focus-visible,
.icon-btn.active{
  color:var(--cyan);
  border-color:var(--line-strong);
  background:rgba(95,216,255,.12);
}

.icon-btn:hover{
  transform:translateY(-1px);
}

.icon-btn:focus-visible,
.settings-menu button:focus-visible,
.mini-close:focus-visible,
.dialog-close:focus-visible,
.picker-close:focus-visible,
.save-btn:focus-visible,
.upload-btn:focus-visible,
.ghost-btn:focus-visible,
.file-btn:focus-visible,
.picker-trigger:focus-visible,
.text-input:focus{
  outline:none;
  box-shadow:0 0 0 2px rgba(95,216,255,.24);
}

.settings-menu,
.diagnostics-popover{
  position:absolute;
  top:calc(100% + 10px);
  right:0;
  display:none;
  border:1px solid var(--line);
  background:linear-gradient(180deg,rgba(10,19,35,.98) 0%,rgba(5,10,20,.98) 100%);
  box-shadow:var(--shadow);
  backdrop-filter:blur(18px);
}

.settings-menu.open,
.diagnostics-popover.open,
.details-wrap:hover .diagnostics-popover{
  display:block;
}

.settings-menu{
  width:min(300px,calc(100vw - 28px));
  padding:8px;
  border-radius:18px;
}

.settings-menu button{
  width:100%;
  min-height:58px;
  border:none;
  border-radius:12px;
  background:transparent;
  color:var(--text);
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  padding:11px 12px;
  text-align:left;
  cursor:pointer;
  transition:background .18s ease,color .18s ease;
}

.settings-menu button:hover{
  background:rgba(95,216,255,.1);
}

.settings-menu span{
  font-weight:800;
  font-size:14px;
}

.settings-menu small{
  min-width:0;
  color:var(--muted);
  font-size:12px;
  text-align:right;
  overflow:hidden;
  text-overflow:ellipsis;
  white-space:nowrap;
}

.diagnostics-popover{
  width:min(520px,calc(100vw - 28px));
  max-height:min(78svh,680px);
  overflow:auto;
  border-radius:22px;
  padding:14px;
}

.popover-head{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  margin-bottom:12px;
  color:var(--muted-strong);
  font-size:13px;
  font-weight:800;
  letter-spacing:1.2px;
  text-transform:uppercase;
}

.mini-close{
  width:32px;
  height:32px;
  border:1px solid var(--line);
  border-radius:10px;
  background:rgba(18,32,54,.84);
  color:var(--muted);
  font-size:20px;
  line-height:1;
  cursor:pointer;
}

.diagnostics-grid{
  display:grid;
  grid-template-columns:repeat(2,minmax(0,1fr));
  gap:8px;
}

.diag-item{
  min-width:0;
  min-height:78px;
  border:1px solid rgba(125,211,252,.11);
  border-radius:14px;
  background:rgba(16,31,55,.58);
  padding:11px 12px;
  display:flex;
  flex-direction:column;
  justify-content:space-between;
  gap:8px;
}

.diag-item.compact{
  min-height:68px;
}

.diag-item span,
.data-label,
.telemetry-item span,
.run-item span,
.curve-head,
.curve-meta,
.card-title,
.metric-label,
.live-label,
.mini-stat-label,
.field-label{
  text-transform:uppercase;
  letter-spacing:1.3px;
}

.diag-item span{
  color:var(--muted);
  font-size:10px;
}

.diag-item strong{
  min-width:0;
  color:var(--text);
  font-size:17px;
  line-height:1.22;
  font-weight:800;
  overflow-wrap:anywhere;
}

.diag-item small{
  color:var(--muted);
  font-size:11px;
  line-height:1.35;
}

.hud-main{
  min-height:0;
  display:grid;
  grid-template-rows:minmax(0,1fr) auto;
  gap:12px;
}

.speed-stage{
  min-height:0;
  position:relative;
  display:grid;
  grid-template-rows:minmax(0,.88fr) minmax(190px,.62fr);
  gap:14px;
  border:1px solid rgba(125,211,252,.08);
  border-radius:28px;
  padding:24px;
  overflow:hidden;
  background:
    linear-gradient(90deg,rgba(95,216,255,.06) 1px,transparent 1px),
    linear-gradient(rgba(95,216,255,.045) 1px,transparent 1px),
    radial-gradient(circle at 18% 42%,rgba(95,216,255,.17),transparent 36%),
    radial-gradient(circle at 74% 34%,rgba(227,25,55,.12),transparent 30%),
    rgba(3,8,18,.52);
  background-size:72px 72px,72px 72px,auto,auto,auto;
  box-shadow:inset 0 1px 0 rgba(255,255,255,.035),0 24px 90px rgba(0,0,0,.28);
}

.speed-stage:before,
.speed-stage:after{
  content:"";
  position:absolute;
  inset:18px;
  border:1px solid rgba(95,216,255,.08);
  border-radius:22px;
  pointer-events:none;
}

.speed-stage:after{
  inset:auto 24px 24px 24px;
  height:1px;
  border:none;
  background:linear-gradient(90deg,transparent,rgba(95,216,255,.5),transparent);
}

.speed-grid{
  min-height:0;
  position:relative;
  z-index:1;
  display:grid;
  grid-template-columns:minmax(0,1fr) minmax(260px,340px);
  gap:22px;
  align-items:center;
}

.speed-primary{
  min-width:0;
}

.data-label{
  color:var(--cyan);
  font-size:12px;
  font-weight:800;
}

.speed-number-row{
  display:flex;
  align-items:flex-end;
  gap:18px;
  margin-top:18px;
}

.speed-value{
  min-width:0;
  font-variant-numeric:tabular-nums;
  font-size:clamp(118px,20vw,260px);
  line-height:.76;
  letter-spacing:0;
  font-weight:900;
  color:var(--text);
  text-shadow:0 0 34px rgba(95,216,255,.28),0 0 7px rgba(255,255,255,.16);
}

.speed-value.is-stale{
  color:#d8e5f6;
  text-shadow:0 0 20px rgba(245,158,11,.24);
}

.speed-value.is-empty{
  font-size:clamp(58px,8vw,118px);
  line-height:.95;
  color:#c9d7ea;
  text-shadow:0 0 18px rgba(95,216,255,.22);
}

.speed-unit{
  padding-bottom:clamp(16px,3.3vw,38px);
  color:var(--muted-strong);
  font-size:clamp(18px,2.2vw,34px);
  line-height:1;
  font-weight:800;
}

.speed-meta{
  margin-top:20px;
  color:var(--muted-strong);
  font-size:clamp(14px,1.35vw,18px);
  line-height:1.45;
}

.side-telemetry{
  display:grid;
  gap:10px;
}

.telemetry-item{
  min-width:0;
  border:none;
  border-left:2px solid rgba(95,216,255,.34);
  border-radius:0;
  background:linear-gradient(90deg,rgba(95,216,255,.08) 0%,transparent 78%);
  padding:13px 0 13px 16px;
}

.run-item{
  min-width:0;
  border:none;
  border-top:1px solid rgba(125,211,252,.18);
  border-radius:0;
  background:linear-gradient(180deg,rgba(95,216,255,.055) 0%,transparent 72%);
  padding:12px 0 0;
}

.telemetry-item span,
.run-item span{
  display:block;
  color:var(--muted);
  font-size:10px;
  font-weight:800;
}

.telemetry-item strong{
  display:block;
  margin-top:9px;
  color:var(--text);
  font-size:clamp(26px,3.4vw,42px);
  line-height:1;
  font-weight:900;
  overflow-wrap:anywhere;
}

.telemetry-item small{
  display:block;
  margin-top:8px;
  color:var(--muted);
  font-size:12px;
  line-height:1.35;
}

.telemetry-item.offset strong,
.telemetry-item.modified strong{
  color:var(--green);
}

.telemetry-item.limit strong{
  color:var(--cyan);
}

.curve-panel{
  min-height:0;
  position:relative;
  z-index:1;
  display:grid;
  grid-template-rows:auto minmax(0,1fr) auto auto;
  gap:8px;
}

.curve-head,
.curve-meta{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  color:var(--muted);
  font-size:12px;
  font-weight:700;
}

.speed-chart-wrap{
  min-height:0;
  position:relative;
}

.speed-chart{
  display:block;
  width:100%;
  height:100%;
  min-height:150px;
}

.speed-chart-grid{
  stroke:rgba(125,211,252,.13);
  stroke-width:1;
  stroke-dasharray:5 8;
}

.speed-chart-area{
  fill:rgba(95,216,255,.15);
}

.speed-chart-line{
  fill:none;
  stroke:var(--cyan);
  stroke-width:3;
  stroke-linecap:square;
  stroke-linejoin:miter;
  filter:drop-shadow(0 0 11px rgba(95,216,255,.42));
}

.speed-chart-samples circle{
  fill:rgba(2,6,13,.92);
  stroke:var(--cyan);
  stroke-width:2;
}

.speed-chart-labels{
  position:absolute;
  inset:0;
  pointer-events:none;
}

.speed-chart-labels span{
  position:absolute;
  color:var(--text);
  font-size:11px;
  font-weight:800;
  line-height:1;
  text-shadow:
    0 0 3px rgba(2,6,13,.96),
    0 0 7px rgba(2,6,13,.96),
    0 0 10px rgba(2,6,13,.96);
  white-space:nowrap;
  transform:translate(-50%,-50%);
}

.speed-chart-labels span.anchor-start{
  transform:translate(0,-50%);
}

.speed-chart-labels span.anchor-end{
  transform:translate(-100%,-50%);
}

.speed-chart-dot{
  fill:var(--text);
  stroke:var(--cyan);
  stroke-width:3;
  opacity:0;
}

.speed-chart-empty{
  position:absolute;
  inset:0;
  display:flex;
  align-items:center;
  justify-content:center;
  border:1px dashed rgba(125,211,252,.14);
  border-radius:18px;
  color:var(--muted);
  background:rgba(2,6,13,.42);
  opacity:0;
  pointer-events:none;
  transition:opacity .2s ease;
}

.speed-chart-empty.visible{
  opacity:1;
}

.curve-meta{
  color:var(--muted-strong);
}

.curve-subline{
  min-height:18px;
  color:var(--muted);
  font-size:12px;
  line-height:1.4;
  text-align:center;
}

.speed-info-value{
  color:var(--text);
  font-weight:900;
}

.run-strip{
  display:grid;
  grid-template-columns:minmax(120px,.6fr) minmax(150px,.7fr) minmax(0,1.7fr);
  gap:10px;
}

.run-item{
  min-height:70px;
  display:flex;
  flex-direction:column;
  justify-content:space-between;
  gap:8px;
}

.run-item strong{
  min-width:0;
  color:var(--text);
  font-size:18px;
  line-height:1.25;
  font-weight:900;
  overflow-wrap:anywhere;
}

.run-item.policy strong{
  color:var(--muted-strong);
  font-size:13px;
  line-height:1.35;
}

.status-text{
  overflow-wrap:anywhere;
}

.status-wide{max-width:none}
.status-ok{color:var(--green) !important}
.status-err{color:var(--red) !important}
.status-warn{color:var(--amber) !important}
.status-yes{color:var(--green) !important}
.status-no{color:#8195b1 !important}
.green{color:var(--green)}
.amber{color:var(--amber)}

.metric-value{
  color:var(--text);
  font-size:inherit;
  line-height:inherit;
  font-weight:900;
}

.row,
.status-row{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  padding:12px 0;
  border-bottom:1px solid rgba(148,163,184,.14);
}

.row:last-child,
.status-row:last-child{
  border-bottom:none;
}

.row-compact{
  padding-top:0;
}

.row-label{
  min-width:0;
  flex:1;
  color:var(--text);
  font-size:14px;
  font-weight:650;
}

.toggle{
  position:relative;
  width:52px;
  height:30px;
  flex:0 0 auto;
}

.toggle input{
  opacity:0;
  width:0;
  height:0;
}

.slider{
  position:absolute;
  inset:0;
  border-radius:999px;
  background:#30415e;
  cursor:pointer;
  transition:background .2s ease;
}

.slider:before{
  content:"";
  position:absolute;
  left:4px;
  bottom:4px;
  width:22px;
  height:22px;
  border-radius:50%;
  background:#fff;
  transition:transform .2s ease;
}

input:checked+.slider{
  background:var(--green);
}

input:checked+.slider:before{
  transform:translateX(22px);
}

input:disabled+.slider{
  opacity:.45;
  cursor:not-allowed;
}

.field{
  padding:12px 0;
}

.field+.field{
  border-top:1px solid rgba(148,163,184,.14);
}

.field-label{
  display:block;
  margin-bottom:8px;
  color:var(--muted);
  font-size:11px;
  font-weight:800;
}

select,
.text-input,
.picker-trigger{
  width:100%;
  border:1px solid rgba(125,211,252,.16);
  border-radius:14px;
  background:#13213a;
  color:var(--text);
  padding:12px 14px;
  font-size:14px;
}

.text-input{
  appearance:none;
}

.text-area{
  min-height:118px;
  resize:vertical;
  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
}

.picker-wrap{
  width:100%;
  min-width:0;
}

.picker-native{
  display:none;
}

.picker-trigger{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  text-align:left;
  cursor:pointer;
  transition:background .2s ease,border-color .2s ease,transform .2s ease;
}

.picker-trigger:after{
  content:"";
  width:0;
  height:0;
  border-left:5px solid transparent;
  border-right:5px solid transparent;
  border-top:6px solid var(--muted);
  flex:0 0 auto;
}

.picker-trigger:hover:not(:disabled){
  border-color:var(--line-strong);
  transform:translateY(-1px);
}

.picker-trigger:disabled,
.save-btn:disabled,
.upload-btn:disabled,
.ghost-btn:disabled{
  opacity:.45;
  cursor:not-allowed;
  transform:none;
}

.secondary-btn,
.save-btn,
.upload-btn,
.ghost-btn{
  border-radius:14px;
  padding:11px 14px;
  font-size:14px;
  font-weight:800;
  cursor:pointer;
  transition:background .2s ease,border-color .2s ease,transform .2s ease;
}

.ghost-btn.small-btn{
  padding:8px 12px;
  font-size:12px;
  flex:0 0 auto;
}

.secondary-btn,
.ghost-btn{
  border:1px solid rgba(125,211,252,.16);
  background:rgba(19,33,58,.85);
  color:var(--text);
}

.save-btn,
.upload-btn{
  border:none;
  background:linear-gradient(180deg,#ff4d67 0%,var(--tesla) 100%);
  color:#fff;
}

.secondary-btn:hover:not(:disabled),
.save-btn:hover:not(:disabled),
.upload-btn:hover:not(:disabled),
.ghost-btn:hover:not(:disabled),
.file-btn:hover{
  transform:translateY(-1px);
  border-color:var(--line-strong);
}

.actions{
  display:flex;
  gap:10px;
  margin-top:14px;
}

.actions>button{
  flex:1;
}

.hint{
  margin-top:8px;
  color:var(--muted);
  font-size:12px;
  line-height:1.55;
}

.msg{
  min-height:16px;
  margin-top:8px;
  text-align:left;
  color:var(--muted);
  font-size:12px;
  line-height:1.5;
  white-space:pre-line;
}

.msg.ok{color:var(--green)}
.msg.err{color:var(--red)}

.inline-actions,
.section-head{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:10px;
}

.section-head{
  margin-top:14px;
}

.inline-actions .field-label,
.section-head .field-label{
  margin-bottom:0;
}

.saved-list{
  display:flex;
  flex-direction:column;
  gap:10px;
  margin-top:12px;
}

.saved-item{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  border:1px solid rgba(125,211,252,.1);
  border-radius:16px;
  background:rgba(18,29,51,.78);
  padding:12px 14px;
}

.saved-main{
  min-width:0;
  flex:1;
}

.saved-name{
  color:var(--text);
  font-size:14px;
  font-weight:800;
  word-break:break-word;
}

.saved-tags{
  display:flex;
  flex-wrap:wrap;
  gap:6px;
  margin-top:8px;
}

.tag{
  display:inline-flex;
  align-items:center;
  padding:4px 8px;
  border-radius:999px;
  background:#26344c;
  color:var(--muted);
  font-size:11px;
  line-height:1;
}

.tag.ok{background:rgba(34,197,94,.16);color:#98f5b9}
.tag.busy{background:rgba(95,216,255,.16);color:#a9ecff}
.tag.warn{background:rgba(245,158,11,.16);color:#fbd38d}

.empty-box{
  border:1px dashed rgba(125,211,252,.16);
  border-radius:16px;
  padding:16px;
  text-align:center;
  color:var(--muted);
  font-size:12px;
}

.ota-row{
  display:flex;
  align-items:center;
  gap:10px;
  flex-wrap:wrap;
}

.file-btn{
  display:inline-flex;
  align-items:center;
  justify-content:center;
  border:1px solid rgba(125,211,252,.16);
  border-radius:14px;
  background:rgba(19,33,58,.85);
  color:var(--text);
  padding:10px 14px;
  font-size:13px;
  font-weight:800;
  cursor:pointer;
  transition:transform .2s ease,border-color .2s ease;
}

.file-name{
  min-width:0;
  flex:1;
  color:var(--muted);
  font-size:12px;
  word-break:break-word;
}

.progress{
  width:100%;
  height:6px;
  margin-top:12px;
  display:none;
  border-radius:999px;
  background:rgba(19,33,58,.92);
  overflow:hidden;
}

.progress-bar{
  width:0%;
  height:100%;
  background:linear-gradient(90deg,var(--green) 0%,#7df3a7 100%);
  transition:width .3s ease;
}

.dialog-modal{
  position:fixed;
  inset:0;
  display:none;
  align-items:center;
  justify-content:center;
  padding:16px;
  background:rgba(3,8,18,.76);
  backdrop-filter:blur(8px);
  z-index:9000;
}

.dialog-modal.open{
  display:flex;
}

.dialog-sheet,
.picker-sheet{
  border:1px solid var(--line);
  background:linear-gradient(180deg,rgba(20,32,54,.96) 0%,rgba(8,14,27,.98) 100%);
  box-shadow:var(--shadow);
}

.dialog-sheet{
  width:min(1120px,100%);
  max-height:min(92svh,900px);
  border-radius:26px;
  overflow:hidden;
  display:grid;
  grid-template-rows:auto minmax(0,1fr);
}

.dialog-sheet.narrow{
  width:min(780px,100%);
}

.dialog-head{
  display:flex;
  align-items:flex-start;
  justify-content:space-between;
  gap:16px;
  padding:18px 20px;
  border-bottom:1px solid rgba(125,211,252,.12);
  background:rgba(11,19,35,.96);
}

.dialog-title-wrap h3{
  color:var(--text);
  font-size:24px;
  font-weight:900;
}

.dialog-title-wrap p{
  margin-top:8px;
  color:var(--muted);
  font-size:13px;
  line-height:1.6;
}

.dialog-close{
  width:40px;
  height:40px;
  border:1px solid rgba(125,211,252,.14);
  border-radius:12px;
  background:rgba(19,33,58,.9);
  color:var(--muted);
  font-size:24px;
  line-height:1;
  cursor:pointer;
  transition:background .2s ease,border-color .2s ease,transform .2s ease;
}

.dialog-close:hover,
.dialog-close:focus-visible{
  border-color:var(--line-strong);
  color:var(--cyan);
}

.dialog-body{
  min-height:0;
  overflow:auto;
  padding:18px;
  display:grid;
  gap:16px;
  background:linear-gradient(180deg,rgba(7,12,22,.98) 0%,rgba(6,10,18,.98) 100%);
}

.dialog-grid{
  grid-template-columns:repeat(2,minmax(0,1fr));
}

.dialog-card{
  border:1px solid rgba(125,211,252,.1);
  border-radius:20px;
  padding:18px;
  background:rgba(18,29,51,.74);
}

.dialog-card.full{
  grid-column:1 / -1;
}

.card-title{
  margin-bottom:10px;
  color:var(--muted);
  font-size:11px;
  font-weight:800;
}

.status-grid{
  display:grid;
  grid-template-columns:repeat(2,minmax(0,1fr));
  gap:0 16px;
}

.status-row span:first-child{
  color:var(--muted);
  font-size:13px;
}

.status-row .status-text{
  max-width:60%;
  text-align:right;
  font-size:14px;
  font-weight:800;
}

.picker-modal{
  position:fixed;
  inset:0;
  display:none;
  align-items:flex-end;
  justify-content:center;
  padding:16px;
  background:rgba(2,8,23,.76);
  z-index:9999;
}

.picker-modal.open{
  display:flex;
}

.picker-sheet{
  width:min(560px,100%);
  max-height:min(80svh,640px);
  border-radius:22px;
  overflow:hidden;
}

.picker-head{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  padding:16px 18px;
  border-bottom:1px solid rgba(125,211,252,.12);
}

.picker-title{
  color:var(--text);
  font-size:15px;
  font-weight:800;
}

.picker-close{
  border:none;
  background:transparent;
  color:var(--muted);
  font-size:22px;
  line-height:1;
  cursor:pointer;
}

.picker-body{
  max-height:min(60svh,520px);
  overflow:auto;
  padding:10px;
}

.picker-option{
  width:100%;
  border:none;
  border-radius:14px;
  background:#172339;
  color:var(--text);
  padding:14px 16px;
  font-size:15px;
  text-align:left;
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:12px;
  cursor:pointer;
}

.picker-option+.picker-option{
  margin-top:8px;
}

.picker-option.active{
  background:rgba(95,216,255,.16);
  color:var(--cyan);
}

.picker-option:after{
  content:"";
  width:10px;
  height:10px;
  border-radius:50%;
  border:2px solid currentColor;
  opacity:.3;
}

.picker-option.active:after{
  opacity:1;
  background:currentColor;
}

@media (max-width:980px){
  body{
    overflow-x:hidden;
    overflow-y:auto;
  }

  .page{
    height:auto;
    min-height:calc(100svh - 28px);
  }

  .app-shell{
    grid-template-rows:auto;
  }

  .speed-stage{
    grid-template-rows:auto auto;
    padding:18px;
  }

  .speed-grid{
    grid-template-columns:1fr;
    align-items:start;
    gap:18px;
  }

  .side-telemetry{
    grid-template-columns:repeat(3,minmax(0,1fr));
  }

  .speed-value{
    font-size:clamp(92px,27vw,180px);
  }

  .speed-chart{
    height:220px;
  }

  .run-strip{
    grid-template-columns:repeat(2,minmax(0,1fr));
  }

  .run-item.policy{
    grid-column:1 / -1;
  }
}

@media (max-width:720px){
  body{
    padding:10px;
  }

  .page{
    min-height:calc(100svh - 20px);
  }

  .hud-topbar{
    align-items:flex-start;
  }

  .hud-identity{
    flex-wrap:wrap;
    padding-top:6px;
  }

  .hud-divider{
    display:none;
  }

  .speed-stage{
    border-radius:22px;
    padding:14px;
  }

  .speed-stage:before{
    inset:12px;
    border-radius:18px;
  }

  .speed-number-row{
    gap:10px;
    margin-top:14px;
  }

  .speed-value{
    font-size:clamp(72px,26vw,130px);
  }

  .speed-unit{
    padding-bottom:14px;
    font-size:18px;
  }

  .speed-meta{
    margin-top:14px;
    font-size:13px;
  }

  .side-telemetry,
  .run-strip,
  .diagnostics-grid,
  .dialog-grid,
  .status-grid{
    grid-template-columns:1fr;
  }

  .telemetry-item{
    padding:12px 14px;
  }

  .telemetry-item strong{
    font-size:28px;
  }

  .speed-chart{
    height:176px;
    min-height:176px;
  }

  .curve-head,
  .curve-meta{
    font-size:11px;
  }

  .run-item.policy{
    grid-column:auto;
  }

  .dialog-modal,
  .picker-modal{
    padding:10px;
  }

  .dialog-body{
    padding:14px;
  }

  .dialog-title-wrap p{
    font-size:12px;
    line-height:1.5;
  }

  .actions,
  .inline-actions,
  .section-head,
  .saved-item,
  .ota-row{
    align-items:stretch;
    flex-direction:column;
  }
}

@media (max-width:420px){
  .hud-actions{
    gap:6px;
  }

  .icon-btn{
    width:44px;
    height:44px;
    border-radius:14px;
  }

  .speed-value{
    font-size:clamp(62px,25vw,98px);
  }

  .speed-unit{
    font-size:15px;
  }

  .settings-menu,
  .diagnostics-popover{
    right:-2px;
  }

  .status-row{
    align-items:flex-start;
    flex-direction:column;
  }

  .status-row .status-text{
    max-width:none;
    text-align:left;
  }
}

@media (max-height:760px) and (min-width:981px){
  body{
    overflow-x:hidden;
    overflow-y:auto;
  }

  .page{
    height:auto;
    min-height:calc(100svh - 28px);
  }

  .speed-stage{
    grid-template-rows:auto auto;
  }

  .speed-value{
    font-size:clamp(98px,16vw,190px);
  }

  .speed-chart{
    height:170px;
  }
}

@media (prefers-reduced-motion:reduce){
  *,
  *:before,
  *:after{
    animation:none !important;
    transition:none !important;
    scroll-behavior:auto !important;
  }
}
</style>
  </head>
  <body>
    <div class="page app-shell">
      <header class="hud-topbar">
        <div class="hud-identity">
          <span class="live-dot" aria-hidden="true"></span>
          <span class="hud-name">FSD 控制器</span>
          <span class="hud-divider"></span>
          <span id="hwModeBadge">硬件 --</span>
        </div>

        <div class="hud-actions">
          <div
            class="hud-popover-wrap details-wrap"
            onmouseenter="showDiagnosticsPanel()"
            onmouseleave="hideDiagnosticsPanelSoon()"
          >
            <button
              type="button"
              class="icon-btn"
              aria-label="查看诊断信息"
              aria-expanded="false"
              id="diagnosticsToggle"
              onclick="toggleDiagnosticsPanel(event)"
            >
              <svg viewBox="0 0 24 24" aria-hidden="true">
                <circle cx="12" cy="12" r="9"></circle>
                <path d="M12 10v7"></path>
                <path d="M12 7h.01"></path>
              </svg>
            </button>

            <aside
              class="diagnostics-popover"
              id="diagnosticsPanel"
              onclick="event.stopPropagation()"
            >
              <div class="popover-head">
                <span>诊断信息</span>
                <button
                  type="button"
                  class="mini-close"
                  aria-label="关闭诊断信息"
                  onclick="closeDiagnosticsPanel()"
                >
                  &times;
                </button>
              </div>
              <div class="diagnostics-grid">
                <div class="diag-item">
                  <span>收包变化</span>
                  <strong id="sRX" class="status-no status-text">--</strong>
                  <small id="sRXMeta">等待速率采样</small>
                </div>
                <div class="diag-item">
                  <span>CAN 总线</span>
                  <strong id="sCAN" class="status-no status-text">等待</strong>
                  <small id="sCANMeta">等待第一帧 CAN</small>
                </div>
                <div class="diag-item compact">
                  <span>错误</span>
                  <strong id="sErrors" class="amber">0</strong>
                </div>
                <div class="diag-item compact">
                  <span>运行时间</span>
                  <strong id="sUptime">0秒</strong>
                </div>
                <div class="diag-item compact">
                  <span>FSD 触发</span>
                  <strong id="sFSD" class="status-no status-text">--</strong>
                </div>
                <div class="diag-item compact">
                  <span>温控</span>
                  <strong id="sThermal" class="status-no status-text">--</strong>
                </div>
                <div class="diag-item">
                  <span>当前热点</span>
                  <strong
                    id="sCurrentUpstream"
                    class="status-no status-text status-wide"
                    >--</strong
                  >
                </div>
                <div class="diag-item compact">
                  <span>RSSI</span>
                  <strong id="sUpstreamRSSI" class="status-no status-text"
                    >--</strong
                  >
                </div>
                <div class="diag-item compact">
                  <span>AP 客户端</span>
                  <strong id="sAPClients" class="status-no status-text">0</strong>
                </div>
                <div class="diag-item compact">
                  <span>DNS</span>
                  <strong
                    id="sDNSMode"
                    class="status-no status-text status-wide"
                    >--</strong
                  >
                </div>
                <div class="diag-item compact">
                  <span>白名单</span>
                  <strong id="sDNSCount" class="status-no status-text">0</strong>
                </div>
                <div class="diag-item compact">
                  <span>已拦截</span>
                  <strong id="sDNSBlocked" class="status-no status-text">0</strong>
                </div>
                <div class="diag-item">
                  <span>本地 AP</span>
                  <strong id="sAP" class="status-ok status-text">--</strong>
                </div>
              </div>
            </aside>
          </div>

          <div class="hud-popover-wrap">
            <button
              type="button"
              class="icon-btn"
              aria-label="打开设置"
              aria-expanded="false"
              id="settingsToggle"
              onclick="toggleSettingsMenu(event)"
            >
              <svg viewBox="0 0 24 24" aria-hidden="true">
                <path
                  d="M12 15.5A3.5 3.5 0 1 0 12 8a3.5 3.5 0 0 0 0 7.5Z"
                ></path>
                <path
                  d="M19.4 15a1.7 1.7 0 0 0 .34 1.87l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .55l-.08.08a2 2 0 0 1-3.42-1.41v-.08A1.7 1.7 0 0 0 9.5 17a1.7 1.7 0 0 0-1.87.34l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.7 1.7 0 0 0 5.1 12a1.7 1.7 0 0 0-.55-1l-.08-.08A2 2 0 0 1 5.88 7.5h.08A1.7 1.7 0 0 0 7.5 6.5a1.7 1.7 0 0 0-.34-1.87l-.06-.06A2 2 0 0 1 9.93 1.74l.06.06A1.7 1.7 0 0 0 12 2.1a1.7 1.7 0 0 0 1-.55l.08-.08A2 2 0 0 1 16.5 2.88v.08A1.7 1.7 0 0 0 17.5 4.5a1.7 1.7 0 0 0 1.87-.34l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.7 1.7 0 0 0 21.9 9a1.7 1.7 0 0 0 .55 1l.08.08a2 2 0 0 1-1.41 3.42h-.08A1.7 1.7 0 0 0 19.4 15Z"
                ></path>
              </svg>
            </button>

            <nav
              class="settings-menu"
              id="settingsMenu"
              onclick="event.stopPropagation()"
            >
              <button type="button" onclick="openDashboardDialog('fsdModal')">
                <span>FSD 设置</span>
                <small id="toolbarFsdMeta">硬件 --</small>
              </button>
              <button type="button" onclick="openDashboardDialog('dnsModal')">
                <span>白名单过滤</span>
                <small id="toolbarDnsMeta">规则 --</small>
              </button>
              <button
                type="button"
                onclick="openDashboardDialog('networkModal')"
              >
                <span>网络热点</span>
                <small id="toolbarNetworkMeta">上游 --</small>
              </button>
              <button type="button" onclick="openDashboardDialog('otaModal')">
                <span>固件升级</span>
                <small>上传 .bin</small>
              </button>
            </nav>
          </div>
        </div>
      </header>

      <main class="hud-main">
        <section class="speed-stage" aria-label="实时车速">
          <div class="speed-grid">
            <div class="speed-primary">
              <div class="data-label">车辆当前速度</div>
              <div class="speed-number-row">
                <div class="speed-value is-empty" id="vehicleSpeedDisplay">
                  等待
                </div>
                <div class="speed-unit">km/h</div>
              </div>
              <div class="speed-meta" id="vehicleSpeedMeta">等待 CAN 车速</div>
            </div>

            <div class="side-telemetry">
              <div class="telemetry-item limit">
                <span>识别限速</span>
                <strong id="detectedSpeedLimitDisplay">--</strong>
                <small id="detectedSpeedSourceDisplay">--</small>
              </div>
              <div class="telemetry-item offset">
                <span>当前增量</span>
                <strong id="speedOffsetDisplay">+0 km/h</strong>
                <small id="speedOffsetState">读取中</small>
              </div>
              <div class="telemetry-item modified">
                <span>改包变化</span>
                <strong id="sModified" class="status-no">--</strong>
                <small id="sModifiedMeta">等待速率采样</small>
              </div>
            </div>
          </div>

          <div class="curve-panel">
            <div class="curve-head">
              <span>最近 1 分钟速度变化</span>
              <span id="vehicleSpeedTrendMeta">波动 --</span>
            </div>
            <div class="speed-chart-wrap">
              <svg
                class="speed-chart"
                viewBox="0 0 320 128"
                preserveAspectRatio="none"
                aria-label="最近 1 分钟速度变化曲线"
                role="img"
              >
                <line
                  class="speed-chart-grid"
                  x1="0"
                  y1="20"
                  x2="320"
                  y2="20"
                ></line>
                <line
                  class="speed-chart-grid"
                  x1="0"
                  y1="64"
                  x2="320"
                  y2="64"
                ></line>
                <line
                  class="speed-chart-grid"
                  x1="0"
                  y1="108"
                  x2="320"
                  y2="108"
                ></line>
                <path
                  id="vehicleSpeedChartArea"
                  class="speed-chart-area"
                  d=""
                ></path>
                <polyline
                  id="vehicleSpeedChartLine"
                  class="speed-chart-line"
                  points=""
                ></polyline>
                <g
                  id="vehicleSpeedChartSamples"
                  class="speed-chart-samples"
                ></g>
                <circle
                  id="vehicleSpeedChartDot"
                  class="speed-chart-dot"
                  cx="0"
                  cy="0"
                  r="4"
                ></circle>
              </svg>
              <div
                id="vehicleSpeedChartLabels"
                class="speed-chart-labels"
                aria-hidden="true"
              ></div>
              <div class="speed-chart-empty" id="vehicleSpeedChartEmpty">
                等待最近车速样本
              </div>
            </div>
            <div class="curve-meta">
              <span id="vehicleSpeedChartMin">最低 --</span>
              <span id="vehicleAccelerationDisplay">--</span>
              <span id="vehicleSpeedChartMax">最高 --</span>
            </div>
            <div class="curve-subline" id="vehicleAccelerationMeta">
              按最近速度变化估算
            </div>
          </div>
        </section>

        <section class="run-strip" aria-label="运行摘要">
          <div class="run-item">
            <span>热点</span>
            <strong id="sUpstream" class="status-no status-text">--</strong>
          </div>
          <div class="run-item">
            <span>芯片温度</span>
            <strong id="sChipTemp" class="status-no status-text status-wide"
              >--</strong
            >
          </div>
          <div class="run-item policy">
            <span>策略</span>
            <strong id="speedPolicySummary"
              >低速更积极，高速 100+ 不超过 10%</strong
            >
          </div>
        </section>
      </main>
    </div>

    <div
      class="dialog-modal"
      id="fsdModal"
      onclick="closeDialog(event,'fsdModal')"
    >
      <div class="dialog-sheet narrow" onclick="event.stopPropagation()">
        <div class="dialog-head">
          <div class="dialog-title-wrap">
            <h3>FSD 设置</h3>
            <p>除了 HW3 速度偏移之外的控制项，都收进这里，避免首页被稀释。</p>
          </div>
          <button
            type="button"
            class="dialog-close"
            onclick="closeDialog(null,'fsdModal')"
          >
            &times;
          </button>
        </div>
        <div class="dialog-body">
          <div class="dialog-card">
            <div class="card-title">基础控制</div>
            <div class="row">
              <span class="row-label">FSD 开关</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="fsdEnable"
                  checked
                  onchange="setVal('fsdEnable',this.checked?1:0)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
            <div class="row">
              <span class="row-label">硬件版本</span>
              <div class="picker-wrap">
                <select
                  id="hwMode"
                  class="picker-native"
                  data-picker-title="硬件版本"
                  data-picker-trigger="hwModeBtn"
                  onchange="setVal('hwMode',this.value)"
                >
                  <option value="0">LEGACY</option>
                  <option value="1">HW3</option>
                  <option value="2" selected>HW4</option>
                </select>
                <button
                  type="button"
                  class="picker-trigger"
                  id="hwModeBtn"
                  onclick="openPicker('hwMode')"
                ></button>
              </div>
            </div>
            <div class="row">
              <span class="row-label">速度模式</span>
              <div class="picker-wrap">
                <select
                  id="speedProfile"
                  class="picker-native"
                  data-picker-title="速度模式"
                  data-picker-trigger="speedProfileBtn"
                  onchange="setVal('speedProfile',this.value)"
                >
                  <option value="0">保守</option>
                  <option value="1" selected>默认</option>
                  <option value="2">适中</option>
                  <option value="3">激进</option>
                  <option value="4">最大</option>
                </select>
                <button
                  type="button"
                  class="picker-trigger"
                  id="speedProfileBtn"
                  onclick="openPicker('speedProfile')"
                ></button>
              </div>
            </div>
            <div class="row">
              <span class="row-label">模式来源</span>
              <div class="picker-wrap">
                <select
                  id="profileMode"
                  class="picker-native"
                  data-picker-title="模式来源"
                  data-picker-trigger="profileModeBtn"
                  onchange="setVal('profileMode',this.value)"
                >
                  <option value="1" selected>自动（拨杆）</option>
                  <option value="0">手动</option>
                </select>
                <button
                  type="button"
                  class="picker-trigger"
                  id="profileModeBtn"
                  onclick="openPicker('profileMode')"
                ></button>
              </div>
            </div>
          </div>

          <div class="dialog-card">
            <div class="card-title">附加功能</div>
            <div class="row">
              <span class="row-label">限速提示音抑制</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="isaChime"
                  onchange="setVal('isaChime',this.checked?1:0)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
            <div class="row">
              <span class="row-label">紧急车辆检测</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="emergencyDet"
                  checked
                  onchange="setVal('emergencyDet',this.checked?1:0)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
            <div class="row">
              <span class="row-label">中国模式</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="chinaMode"
                  onchange="setVal('chinaMode',this.checked?1:0)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div
      class="dialog-modal"
      id="dnsModal"
      onclick="closeDialog(event,'dnsModal')"
    >
      <div class="dialog-sheet" onclick="event.stopPropagation()">
        <div class="dialog-head">
          <div class="dialog-title-wrap">
            <h3>白名单过滤</h3>
            <p>
              白名单、黑名单与最近被拦截请求都收进这个弹窗，首页只保留结果状态。
            </p>
          </div>
          <button
            type="button"
            class="dialog-close"
            onclick="closeDialog(null,'dnsModal')"
          >
            &times;
          </button>
        </div>
        <div class="dialog-body dialog-grid">
          <div class="dialog-card">
            <div class="card-title">规则控制</div>
            <div class="row">
              <span class="row-label">启用 DNS 规则</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="dnsWhitelistEnable"
                  onchange="markDnsDirty()" /><span class="slider"></span
              ></label>
            </div>
            <div class="field">
              <label class="field-label" for="dnsAllowlist"
                >允许解析的域名</label
              >
              <textarea
                class="text-input text-area"
                id="dnsAllowlist"
                maxlength="384"
                placeholder="每行一个域名，例如：&#10;tesla.com&#10;apple.com"
                oninput="markDnsDirty()"
              ></textarea>
            </div>
            <div class="field">
              <label class="field-label" for="dnsBlocklist"
                >禁止解析的域名</label
              >
              <textarea
                class="text-input text-area"
                id="dnsBlocklist"
                maxlength="384"
                placeholder="每行一个域名，例如：&#10;google.com&#10;doubleclick.net"
                oninput="markDnsDirty()"
              ></textarea>
            </div>
            <div class="hint">
              支持逗号、空格或换行分隔。填写 `tesla.com` 会同时允许
              `api.tesla.com` 这类子域名。
            </div>
            <div class="hint">
              黑名单优先于白名单。若白名单留空，则表示“除黑名单外全部放行”；白名单非空时，只允许解析白名单域名。
            </div>
            <div class="actions">
              <button class="save-btn" onclick="saveDns()">
                保存 DNS 规则
              </button>
            </div>
            <div class="msg" id="dnsMsg"></div>
          </div>

          <div class="dialog-card">
            <div class="card-title">过滤状态</div>
            <div class="status-row">
              <span>黑名单数量</span
              ><span id="sDNSBlockCount" class="status-no status-text">0</span>
            </div>
            <div class="hint">
              首页会实时显示 DNS
              总状态、白名单条数和拦截总数，这里只看详细记录。
            </div>
            <div class="section-head">
              <div class="field-label">最近被拦截请求</div>
              <button class="ghost-btn small-btn" onclick="clearBlockedDns()">
                清空记录
              </button>
            </div>
            <div class="hint">按域名聚合统计被拦截次数，设备重启后会清空。</div>
            <div class="saved-list" id="dnsBlockedList"></div>
          </div>
        </div>
      </div>
    </div>

    <div
      class="dialog-modal"
      id="networkModal"
      onclick="closeDialog(event,'networkModal')"
    >
      <div class="dialog-sheet" onclick="event.stopPropagation()">
        <div class="dialog-head">
          <div class="dialog-title-wrap">
            <h3>网络热点</h3>
            <p>
              本地 AP、上游热点与 NAT 明细放在这里，首页仅保留连接状态摘要。
            </p>
          </div>
          <button
            type="button"
            class="dialog-close"
            onclick="closeDialog(null,'networkModal')"
          >
            &times;
          </button>
        </div>
        <div class="dialog-body dialog-grid">
          <div class="dialog-card">
            <div class="card-title">本地热点</div>
            <div class="field">
              <label class="field-label" for="apSSID">本地热点名称</label>
              <input
                class="text-input"
                type="text"
                id="apSSID"
                maxlength="32"
                placeholder="例如：FSD-Controller"
                oninput="markApDirty()"
              />
            </div>
            <div class="field">
              <label class="field-label" for="apPass">本地热点密码</label>
              <input
                class="text-input"
                type="password"
                id="apPass"
                maxlength="63"
                placeholder="8-63 个字符"
                oninput="markApDirty()"
              />
            </div>
            <div class="actions">
              <button class="save-btn" onclick="saveApConfig()">
                保存本地热点
              </button>
            </div>
            <div class="msg" id="apMsg"></div>
            <div class="hint">
              保存后设备会重启本地
              AP，当前连接会断开，请重新连接新的热点名称和密码。
            </div>
            <div class="status-row">
              <span>AP 地址</span
              ><span id="sAPIP" class="status-ok status-text">--</span>
            </div>
          </div>

          <div class="dialog-card">
            <div class="card-title">上游热点</div>
            <div class="row">
              <span class="row-label">启用手机热点接入</span>
              <label class="toggle"
                ><input
                  type="checkbox"
                  id="upstreamEnable"
                  onchange="setUpstreamEnabled(this.checked)" /><span
                  class="slider"
                ></span
              ></label>
            </div>
            <div class="field">
              <div class="inline-actions">
                <label class="field-label" for="scanResults"
                  >搜索附近热点</label
                >
                <button
                  class="ghost-btn small-btn"
                  id="scanBtn"
                  onclick="scanUpstreamNetworks()"
                >
                  搜索热点
                </button>
              </div>
              <div class="picker-wrap">
                <select
                  id="scanResults"
                  class="picker-native"
                  data-picker-title="选择附近热点"
                  data-picker-trigger="scanResultsBtn"
                >
                  <option value="">点击“搜索热点”查看附近可用热点</option>
                </select>
                <button
                  type="button"
                  class="picker-trigger"
                  id="scanResultsBtn"
                  onclick="openPicker('scanResults')"
                ></button>
              </div>
            </div>
            <div class="field">
              <label class="field-label" for="upstreamPass">热点密码</label>
              <input
                class="text-input"
                type="password"
                id="upstreamPass"
                maxlength="63"
                placeholder="首次添加或更新密码时填写"
              />
            </div>
            <div class="actions">
              <button class="save-btn" onclick="saveSelectedUpstream()">
                保存选中热点
              </button>
            </div>
            <div class="msg" id="netMsg"></div>
            <div class="hint">
              支持保存多个热点，设备会自动跳过本机发射的
              AP，并优先尝试当前能连上的热点。
            </div>
            <div class="saved-list" id="savedNetworks"></div>
          </div>

          <div class="dialog-card full">
            <div class="card-title">网络状态细节</div>
            <div class="status-grid">
              <div class="status-row">
                <span>已保存热点</span
                ><span id="sSavedUpstreams" class="status-no status-text"
                  >0</span
                >
              </div>
              <div class="status-row">
                <span>信号质量</span
                ><span id="sUpstreamSignal" class="status-no status-text"
                  >--</span
                >
              </div>
              <div class="status-row">
                <span>当前信道</span
                ><span id="sWiFiChannel" class="status-no status-text">--</span>
              </div>
              <div class="status-row">
                <span>上游 IP</span
                ><span id="sUpstreamIP" class="status-no status-text">--</span>
              </div>
              <div class="status-row">
                <span>NAT 转发</span
                ><span id="sNAT" class="status-no status-text">--</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div
      class="dialog-modal"
      id="otaModal"
      onclick="closeDialog(event,'otaModal')"
    >
      <div class="dialog-sheet narrow" onclick="event.stopPropagation()">
        <div class="dialog-head">
          <div class="dialog-title-wrap">
            <h3>固件升级</h3>
            <p>升级入口保留，但不再占用首页面积。</p>
          </div>
          <button
            type="button"
            class="dialog-close"
            onclick="closeDialog(null,'otaModal')"
          >
            &times;
          </button>
        </div>
        <div class="dialog-body">
          <div class="dialog-card">
            <div class="card-title">OTA 更新</div>
            <div class="ota-row">
              <label class="file-btn" for="fwFile">选择文件</label>
              <input
                type="file"
                id="fwFile"
                accept=".bin"
                style="display: none"
                onchange="fileChosen(this)"
              />
              <span class="file-name" id="fileName">未选择文件</span>
            </div>
            <button
              class="upload-btn"
              id="uploadBtn"
              disabled
              onclick="doOTA()"
            >
              上传固件
            </button>
            <div class="progress" id="progWrap">
              <div class="progress-bar" id="progBar"></div>
            </div>
            <div class="msg" id="otaMsg"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="picker-modal" id="pickerModal" onclick="closePicker(event)">
      <div class="picker-sheet" onclick="event.stopPropagation()">
        <div class="picker-head">
          <div class="picker-title" id="pickerTitle">请选择</div>
          <button type="button" class="picker-close" onclick="closePicker()">
            &times;
          </button>
        </div>
        <div class="picker-body" id="pickerBody"></div>
      </div>
    </div>

    <script>
let dnsDirty=false;
let apDirty=false;
let scanResults=[];
let pendingScanResultsRender=false;
let latestBlockedDnsRequests=[];
let latestStatusUptime=0;
let lastCanCounters=null;
let activePickerId='';
let vehicleSpeedHistory=[];
let lastVehicleSpeedUptimeMs=null;
let lastValidVehicleSpeedKph=null;
let diagnosticsPinned=false;
let diagnosticsHideTimer=0;
const COUNTER_WRAP=4294967296;
const VEHICLE_SPEED_HISTORY_WINDOW_MS=60000;
const MAX_VEHICLE_SPEED_POINTS=75;
const VEHICLE_SPEED_META_MAX_AGE_MS=30000;
const SVG_NS='http://www.w3.org/2000/svg';
const OTA_TRACE_POLL_MS=1200;
const OTA_TRACE_TIMEOUT_MS=20000;
let otaTraceTimer=0;
let otaTraceStartedAt=0;
let otaTraceGeneration=0;
let otaTraceController=null;
let otaTraceClientUploadComplete=false;
let otaTraceSawLikelySuccessPhase=false;
let otaClientUploadComplete=false;
const hwModeLabels={
  '0':'LEGACY',
  '1':'HW3',
  '2':'HW4'
};

function setTextIfPresent(id,text){
  const el=document.getElementById(id);
  if(el)el.textContent=text;
}

function markDnsDirty(){
  dnsDirty=true;
  renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
  syncDashboardSummary();
}

function markApDirty(){
  apDirty=true;
}

function setStatusText(id,text,className){
  const el=document.getElementById(id);
  if(!el)return;
  el.textContent=text;
  el.className=className+' status-text';
}

function setWideStatusText(id,text,className){
  const el=document.getElementById(id);
  if(!el)return;
  el.textContent=text;
  el.className=className+' status-text status-wide';
}

function setMetricValue(id,text,className){
  const el=document.getElementById(id);
  if(!el)return;
  el.textContent=text;
  el.className='metric-value '+className;
}

function setSpeedInfoValue(id,text,className){
  const el=document.getElementById(id);
  if(!el)return;
  el.textContent=text;
  el.className='speed-info-value '+className;
}

function formatChipTemp(current,average){
  const currentValid=typeof current==='number'&&Number.isFinite(current);
  const avgValid=typeof average==='number'&&Number.isFinite(average);
  if(!currentValid&&!avgValid)return '--';
  if(currentValid&&avgValid)return current.toFixed(1)+'°C / 平均 '+average.toFixed(1)+'°C';
  if(currentValid)return current.toFixed(1)+'°C';
  return '平均 '+average.toFixed(1)+'°C';
}

function getSignalClass(rssi){
  if(typeof rssi!=='number'||!Number.isFinite(rssi))return 'status-no';
  if(rssi>=-55)return 'status-ok';
  if(rssi>=-67)return 'status-ok';
  if(rssi>=-75)return 'status-warn';
  return 'status-err';
}

function formatActivityAge(ageMs){
  if(typeof ageMs!=='number'||!Number.isFinite(ageMs))return '--';
  if(ageMs<1000)return '不到 1 秒';
  if(ageMs<60000)return String(Math.max(1,Math.round(ageMs/1000)))+' 秒';
  if(ageMs<3600000)return String(Math.round(ageMs/60000))+' 分钟';
  return String(Math.round(ageMs/3600000))+' 小时';
}

function getCounterDelta(current,previous){
  if(typeof current!=='number'||!Number.isFinite(current))return null;
  if(typeof previous!=='number'||!Number.isFinite(previous))return null;
  if(current>=previous)return current-previous;
  return COUNTER_WRAP-previous+current;
}

function updateCounterCard(id,metaId,delta,isActive,ageMs,noun){
  if(delta===null){
    if(isActive){
      setMetricValue(id,'变化中','status-ok');
      setTextIfPresent(metaId,'已检测到'+noun+'，等待下一次速率采样');
    }else if(typeof ageMs==='number'&&Number.isFinite(ageMs)){
      setMetricValue(id,'空闲','status-no');
      setTextIfPresent(metaId,'上次'+noun+' '+formatActivityAge(ageMs)+'前');
    }else{
      setMetricValue(id,'等待','status-no');
      setTextIfPresent(metaId,'尚未检测到'+noun);
    }
    return;
  }

  if(delta>0){
    setMetricValue(id,'+'+String(delta)+'/s','status-ok');
    setTextIfPresent(metaId,'最近 1 秒持续'+noun);
    return;
  }

  setMetricValue(id,'空闲','status-no');
  if(typeof ageMs==='number'&&Number.isFinite(ageMs)){
    setTextIfPresent(metaId,'上次'+noun+' '+formatActivityAge(ageMs)+'前');
  }else{
    setTextIfPresent(metaId,'尚未检测到'+noun);
  }
}

function updateCanActivity(data){
  const rx=typeof data.rx==='number'?data.rx:Number(data.rx||0);
  const modified=typeof data.modified==='number'?data.modified:Number(data.modified||0);
  const rxDelta=lastCanCounters?getCounterDelta(rx,lastCanCounters.rx):null;
  const modifiedDelta=lastCanCounters?getCounterDelta(modified,lastCanCounters.modified):null;

  updateCounterCard('sRX','sRXMeta',rxDelta,!!data.rxActive,data.rxAgeMs,'收包');
  updateCounterCard('sModified','sModifiedMeta',modifiedDelta,!!data.modifiedActive,data.modifiedAgeMs,'改包');

  lastCanCounters={rx,modified};
}

function updateCanStatus(data){
  const canEl=document.getElementById('sCAN');
  if(!canEl)return;

  let text='异常';
  let className='status-err';
  let meta='TWAI 初始化失败';

  if(data.canReady){
    if(data.rxActive){
      text='活跃';
      className='status-ok';
      meta='最近'+formatActivityAge(data.rxAgeMs)+'有收包';
    }else if((typeof data.rx==='number'?data.rx:Number(data.rx||0))>0){
      text='静默';
      className='status-warn';
      meta='驱动已就绪，但最近 2 秒没有新 CAN';
    }else{
      text='等待';
      className='status-no';
      meta='驱动已就绪，等待第一帧 CAN';
    }
  }

  canEl.textContent=text;
  canEl.className=className+' status-text';
  setTextIfPresent('sCANMeta',meta);
}

function getHwModeLabel(value){
  return hwModeLabels[String(value)]||'--';
}

function getSpeedSourceLabel(value){
  switch(String(value)){
    case '1': return '视觉限速';
    case '2': return '融合限速';
    case '3': return '地图限速';
    default: return '';
  }
}

function getVehicleSpeedSourceLabel(value){
  switch(String(value)){
    case '1': return 'ESP 车身速度';
    case '2': return 'DI 仪表车速';
    default: return '';
  }
}

function formatVehicleSpeedAge(ageMs){
  if(typeof ageMs!=='number'||!Number.isFinite(ageMs)||ageMs<0)return '';
  if(ageMs<120)return '刚更新';
  if(ageMs<1000)return String(Math.round(ageMs/10)*10)+' ms前';
  if(ageMs<10000)return (ageMs/1000).toFixed(1)+' 秒前';
  if(ageMs<VEHICLE_SPEED_META_MAX_AGE_MS)return String(Math.round(ageMs/1000))+' 秒前';
  return '';
}

function formatVehicleSpeedValue(speedKph){
  if(typeof speedKph!=='number'||!Number.isFinite(speedKph))return '--';
  return speedKph>=100?String(Math.round(speedKph)):speedKph.toFixed(1);
}

function formatVehicleSpeedLabel(speedKph){
  if(typeof speedKph!=='number'||!Number.isFinite(speedKph))return '--';
  return formatVehicleSpeedValue(speedKph)+' km/h';
}

function trimVehicleSpeedHistory(uptimeMs){
  const minTime=Math.max(0,uptimeMs-VEHICLE_SPEED_HISTORY_WINDOW_MS);
  vehicleSpeedHistory=vehicleSpeedHistory.filter(point=>point.timeMs>=minTime);
  if(vehicleSpeedHistory.length>MAX_VEHICLE_SPEED_POINTS){
    vehicleSpeedHistory=vehicleSpeedHistory.slice(-MAX_VEHICLE_SPEED_POINTS);
  }
}

function resetVehicleSpeedHistory(){
  vehicleSpeedHistory=[];
  lastVehicleSpeedUptimeMs=null;
  lastValidVehicleSpeedKph=null;
}

function updateVehicleSpeedHistory(data){
  const uptimeMs=Math.max(0,Number(data&&data.uptime||0)*1000);
  if(lastVehicleSpeedUptimeMs!==null&&uptimeMs<lastVehicleSpeedUptimeMs){
    resetVehicleSpeedHistory();
  }
  lastVehicleSpeedUptimeMs=uptimeMs;
  trimVehicleSpeedHistory(uptimeMs);

  const speedKph=Number(data&&data.vehicleSpeedKph);
  const speedValid=!!(data&&data.vehicleSpeedValid)&&Number.isFinite(speedKph);
  if(!speedValid)return;

  const lastPoint=vehicleSpeedHistory[vehicleSpeedHistory.length-1];
  if(lastPoint&&lastPoint.timeMs===uptimeMs){
    lastPoint.kph=speedKph;
    return;
  }

  vehicleSpeedHistory.push({timeMs:uptimeMs,kph:speedKph});
  trimVehicleSpeedHistory(uptimeMs);
}

function computeVehicleAccelerationG(){
  if(vehicleSpeedHistory.length<2)return null;
  const latest=vehicleSpeedHistory[vehicleSpeedHistory.length-1];
  let anchor=null;

  for(let i=vehicleSpeedHistory.length-2;i>=0;i--){
    const candidate=vehicleSpeedHistory[i];
    const dtSec=(latest.timeMs-candidate.timeMs)/1000;
    if(dtSec>=1.5&&dtSec<=4){
      anchor=candidate;
      break;
    }
  }

  if(!anchor)anchor=vehicleSpeedHistory[vehicleSpeedHistory.length-2];
  const dtSec=(latest.timeMs-anchor.timeMs)/1000;
  if(dtSec<=0||dtSec>5)return null;

  const accelMps2=((latest.kph-anchor.kph)/3.6)/dtSec;
  return accelMps2/9.80665;
}

function clearSvgChildren(el){
  while(el.firstChild)el.removeChild(el.firstChild);
}

function addVehicleSpeedLabelCandidate(candidates,index,priority){
  const current=candidates.get(index)||0;
  if(priority>current)candidates.set(index,priority);
}

function renderVehicleSpeedChartSamples(samplesEl,labelsEl,points,minKph,maxKph,startTime){
  clearSvgChildren(samplesEl);
  clearSvgChildren(labelsEl);

  points.forEach(point=>{
    const circle=document.createElementNS(SVG_NS,'circle');
    circle.setAttribute('cx',point.x.toFixed(1));
    circle.setAttribute('cy',point.y.toFixed(1));
    circle.setAttribute('r','2.2');
    samplesEl.appendChild(circle);
  });

  const candidates=new Map();
  const lastIndex=points.length-1;
  addVehicleSpeedLabelCandidate(candidates,0,35);
  addVehicleSpeedLabelCandidate(candidates,lastIndex,100);

  const minIndex=points.findIndex(point=>point.kph===minKph);
  const maxIndex=points.findIndex(point=>point.kph===maxKph);
  if(minIndex>=0)addVehicleSpeedLabelCandidate(candidates,minIndex,70);
  if(maxIndex>=0)addVehicleSpeedLabelCandidate(candidates,maxIndex,70);

  let nextTimeMark=startTime+10000;
  points.forEach((point,index)=>{
    const previous=points[index-1];
    if(previous){
      const deltaKph=Math.abs(point.kph-previous.kph);
      if(deltaKph>=3)addVehicleSpeedLabelCandidate(candidates,index,65);
      else if(deltaKph>=1.5)addVehicleSpeedLabelCandidate(candidates,index,50);
    }
    while(point.timeMs>=nextTimeMark){
      addVehicleSpeedLabelCandidate(candidates,index,30);
      nextTimeMark+=10000;
    }
  });

  const selected=[];
  Array.from(candidates.entries())
    .map(([index,priority])=>({point:points[index],priority}))
    .sort((a,b)=>b.priority-a.priority)
    .forEach(candidate=>{
      const overlapIndex=selected.findIndex(item=>Math.abs(item.point.x-candidate.point.x)<42);
      if(overlapIndex>=0){
        if(candidate.priority>selected[overlapIndex].priority){
          selected.splice(overlapIndex,1,candidate);
        }
        return;
      }
      selected.push(candidate);
    });

  selected
    .sort((a,b)=>b.priority-a.priority)
    .slice(0,10)
    .sort((a,b)=>a.point.x-b.point.x)
    .forEach(({point})=>{
      const label=document.createElement('span');
      let y=point.y-8;
      const x=Math.max(8,Math.min(312,point.x));
      if(y<14)y=point.y+16;
      label.style.left=(x/320*100).toFixed(2)+'%';
      label.style.top=(Math.max(12,Math.min(122,y))/128*100).toFixed(2)+'%';
      if(point.x<18)label.className='anchor-start';
      else if(point.x>302)label.className='anchor-end';
      label.textContent=formatVehicleSpeedValue(point.kph);
      labelsEl.appendChild(label);
    });
}

function updateVehicleSpeedChart(){
  const areaEl=document.getElementById('vehicleSpeedChartArea');
  const lineEl=document.getElementById('vehicleSpeedChartLine');
  const samplesEl=document.getElementById('vehicleSpeedChartSamples');
  const labelsEl=document.getElementById('vehicleSpeedChartLabels');
  const dotEl=document.getElementById('vehicleSpeedChartDot');
  const emptyEl=document.getElementById('vehicleSpeedChartEmpty');
  if(!areaEl||!lineEl||!samplesEl||!labelsEl||!dotEl||!emptyEl)return;

  if(vehicleSpeedHistory.length<2){
    areaEl.setAttribute('d','');
    lineEl.setAttribute('points','');
    clearSvgChildren(samplesEl);
    clearSvgChildren(labelsEl);
    dotEl.style.opacity='0';
    emptyEl.classList.add('visible');
    setTextIfPresent('vehicleSpeedTrendMeta','波动 --');
    setTextIfPresent('vehicleSpeedChartMin','最低 --');
    setTextIfPresent('vehicleSpeedChartMax','最高 --');
    return;
  }

  const width=320;
  const top=16;
  const bottom=108;
  const height=bottom-top;
  const latestTime=vehicleSpeedHistory[vehicleSpeedHistory.length-1].timeMs;
  const startTime=Math.max(0,latestTime-VEHICLE_SPEED_HISTORY_WINDOW_MS);
  const minKph=Math.min(...vehicleSpeedHistory.map(point=>point.kph));
  const maxKph=Math.max(...vehicleSpeedHistory.map(point=>point.kph));
  const rangeKph=Math.max(4,maxKph-minKph);

  const points=vehicleSpeedHistory.map(point=>{
    const x=((point.timeMs-startTime)/VEHICLE_SPEED_HISTORY_WINDOW_MS)*width;
    const y=bottom-((point.kph-minKph)/rangeKph)*height;
    return {
      x:Math.max(0,Math.min(width,x)),
      y:Math.max(top,Math.min(bottom,y)),
      kph:point.kph,
      timeMs:point.timeMs
    };
  });

  const steppedPoints=[];
  points.forEach((point,index)=>{
    if(index===0){
      steppedPoints.push(point);
      return;
    }
    const previous=points[index-1];
    steppedPoints.push({x:point.x,y:previous.y});
    steppedPoints.push(point);
  });

  const polylinePoints=steppedPoints.map(point=>point.x.toFixed(1)+','+point.y.toFixed(1)).join(' ');
  const linePath=steppedPoints.map((point,index)=>(index===0?'M ':' L ')+point.x.toFixed(1)+' '+point.y.toFixed(1)).join('');
  const firstPoint=points[0];
  const lastPoint=points[points.length-1];

  areaEl.setAttribute('d',linePath+' L '+lastPoint.x.toFixed(1)+' '+String(bottom)+' L '+firstPoint.x.toFixed(1)+' '+String(bottom)+' Z');
  lineEl.setAttribute('points',polylinePoints);
  renderVehicleSpeedChartSamples(samplesEl,labelsEl,points,minKph,maxKph,startTime);
  dotEl.setAttribute('cx',lastPoint.x.toFixed(1));
  dotEl.setAttribute('cy',lastPoint.y.toFixed(1));
  dotEl.style.opacity='1';
  emptyEl.classList.remove('visible');
  setTextIfPresent('vehicleSpeedTrendMeta','波动 '+formatVehicleSpeedLabel(maxKph-minKph));
  setTextIfPresent('vehicleSpeedChartMin','最低 '+formatVehicleSpeedLabel(minKph));
  setTextIfPresent('vehicleSpeedChartMax','最高 '+formatVehicleSpeedLabel(maxKph));
}

function updateVehicleAcceleration(speedValid){
  if(!speedValid){
    setSpeedInfoValue('vehicleAccelerationDisplay','--','status-no');
    setTextIfPresent('vehicleAccelerationMeta','等待连续车速样本');
    return;
  }

  const accelG=computeVehicleAccelerationG();
  if(accelG===null||!Number.isFinite(accelG)){
    setSpeedInfoValue('vehicleAccelerationDisplay','--','status-no');
    setTextIfPresent('vehicleAccelerationMeta','至少需要 2 个连续速度点');
    return;
  }

  let className='status-no';
  if(accelG>=0.02)className='status-ok';
  else if(accelG<=-0.02)className='status-warn';

  const accelLabel=(accelG>0?'+':'')+accelG.toFixed(2)+' g';
  setSpeedInfoValue('vehicleAccelerationDisplay',accelLabel,className);
  setTextIfPresent('vehicleAccelerationMeta','按最近 2-4 秒速度变化估算');
}

function updateVehicleSpeedTelemetry(data){
  updateVehicleSpeedHistory(data);

  const speedKph=Number(data&&data.vehicleSpeedKph);
  const speedValid=!!(data&&data.vehicleSpeedValid)&&Number.isFinite(speedKph);
  const speedEl=document.getElementById('vehicleSpeedDisplay');
  if(speedEl){
    if(speedValid){
      lastValidVehicleSpeedKph=speedKph;
      speedEl.textContent=formatVehicleSpeedValue(speedKph);
      speedEl.classList.remove('is-stale');
      speedEl.classList.remove('is-empty');
    }else if(lastValidVehicleSpeedKph!==null){
      speedEl.textContent=formatVehicleSpeedValue(lastValidVehicleSpeedKph);
      speedEl.classList.add('is-stale');
      speedEl.classList.remove('is-empty');
    }else{
      speedEl.textContent='等待';
      speedEl.classList.add('is-stale');
      speedEl.classList.add('is-empty');
    }
  }

  if(speedValid){
    const sourceLabel=getVehicleSpeedSourceLabel(data.vehicleSpeedSource)||'CAN 车速';
    const ageLabel=formatVehicleSpeedAge(Number(data.vehicleSpeedAgeMs));
    setTextIfPresent('vehicleSpeedMeta',[sourceLabel,ageLabel].filter(Boolean).join(' · '));
  }else if(typeof data.vehicleSpeedAgeMs==='number'&&Number.isFinite(data.vehicleSpeedAgeMs)){
    const ageLabel=formatVehicleSpeedAge(data.vehicleSpeedAgeMs);
    setTextIfPresent('vehicleSpeedMeta',ageLabel?'车速数据暂停 · 上次更新 '+ageLabel:'车速数据暂停');
  }else{
    setTextIfPresent('vehicleSpeedMeta','等待 CAN 车速');
  }

  updateVehicleSpeedChart();
  updateVehicleAcceleration(speedValid);
}

function syncDashboardSummary(data){
  const hwSelect=document.getElementById('hwMode');
  const fsdToggle=document.getElementById('fsdEnable');
  const dnsToggle=document.getElementById('dnsWhitelistEnable');
  const currentUpstream=document.getElementById('sCurrentUpstream');
  const upstreamStatus=document.getElementById('sUpstream');
  const hwLabel=data?getHwModeLabel(data.hwMode):getSelectDisplayText(hwSelect);
  const isHw3=data?String(data.hwMode)==='1':hwLabel==='HW3';
  const fsdEnabled=data?!!data.fsdEnable:!!(fsdToggle&&fsdToggle.checked);
  const fsdTriggered=data?!!data.fsdTriggered:false;
  const dnsEnabled=data?!!data.dnsWhitelistEnable:!!(dnsToggle&&dnsToggle.checked);
  const dnsCount=data?Number(data.dnsWhitelistCount||0):getDnsRulesFromTextarea('dnsAllowlist').length;
  const currentUpstreamText=(data?(data.connectedUpstreamSSID||data.upstreamSSID||''):((currentUpstream&&currentUpstream.textContent)||'')).trim();
  const upstreamStatusText=(data?(data.upstreamStatus||'--'):((upstreamStatus&&upstreamStatus.textContent)||'--')).trim();
  const detectedLimitKph=data?Number(data.detectedSpeedLimitKph||0):0;
  const detectedSpeedSource=data?getSpeedSourceLabel(data.detectedSpeedSource):'';
  const appliedOffsetKph=data&&isHw3&&fsdEnabled&&fsdTriggered?Number(data.appliedSpeedOffsetKph||0):0;
  const appliedOffsetLabel='+'+String(appliedOffsetKph)+' km/h';
  const sourceLabel=detectedSpeedSource||'--';
  let offsetState='读取中';
  let policySummary='低于30→30，30→45，40→55，50→65，60→72，70起+10，最高130';
  let limitLabel='--';

  if(data&&detectedLimitKph>0){
    limitLabel=String(detectedLimitKph)+' km/h';
  }

  if(!isHw3){
    offsetState='当前为 '+hwLabel+'，自动限速仅在 HW3 生效';
    policySummary='当前硬件不使用这套 HW3 自动限速策略';
  }else if(data&&!fsdEnabled){
    offsetState='FSD 已关闭，当前仅监测限速';
  }else if(data&&!fsdTriggered){
    offsetState=detectedLimitKph>0?'未触发 FSD，当前仅监测限速':'未触发 FSD，等待车机进入 FSD';
  }else if(data&&detectedLimitKph>0){
    offsetState='按识别限速自动上浮';
  }else if(data){
    offsetState='未识别到有效限速，回退到温和默认增量';
    policySummary+=' · 识别丢失时回退到 +'+String(10)+' km/h 内';
  }

  setTextIfPresent('hwModeBadge','硬件 '+hwLabel);
  setTextIfPresent('speedOffsetDisplay',appliedOffsetLabel);
  setTextIfPresent('speedOffsetState',offsetState);
  setTextIfPresent('detectedSpeedLimitDisplay',limitLabel);
  setTextIfPresent('detectedSpeedSourceDisplay',sourceLabel);
  setTextIfPresent('speedPolicySummary',policySummary);
  setTextIfPresent('toolbarFsdMeta','硬件 '+hwLabel+' · '+(fsdEnabled?'已启用':'已关闭'));
  setTextIfPresent('toolbarDnsMeta',(dnsEnabled?'已启用':'未启用')+' · 白名单 '+dnsCount+' 条');
  setTextIfPresent('toolbarNetworkMeta',currentUpstreamText&&currentUpstreamText!=='--'?currentUpstreamText:'上游 '+(upstreamStatusText||'--'));
}

function openDialog(id){
  const dialog=document.getElementById(id);
  if(dialog)dialog.classList.add('open');
}

function closeDialog(evt,id){
  const dialog=id?document.getElementById(id):(evt&&evt.target&&evt.target.classList.contains('dialog-modal')?evt.target:null);
  if(!dialog)return;
  if(evt&&evt.target&&evt.target!==dialog)return;
  dialog.classList.remove('open');
}

function setExpanded(id,expanded){
  const el=document.getElementById(id);
  if(el)el.setAttribute('aria-expanded',expanded?'true':'false');
}

function closeSettingsMenu(){
  const menu=document.getElementById('settingsMenu');
  const toggle=document.getElementById('settingsToggle');
  if(menu)menu.classList.remove('open');
  if(toggle)toggle.classList.remove('active');
  setExpanded('settingsToggle',false);
}

function closeDiagnosticsPanel(){
  diagnosticsPinned=false;
  const panel=document.getElementById('diagnosticsPanel');
  const toggle=document.getElementById('diagnosticsToggle');
  if(panel)panel.classList.remove('open');
  if(toggle)toggle.classList.remove('active');
  setExpanded('diagnosticsToggle',false);
}

function showDiagnosticsPanel(){
  clearTimeout(diagnosticsHideTimer);
  closeSettingsMenu();
  const panel=document.getElementById('diagnosticsPanel');
  if(panel)panel.classList.add('open');
  const toggle=document.getElementById('diagnosticsToggle');
  if(toggle)toggle.classList.add('active');
  setExpanded('diagnosticsToggle',true);
}

function hideDiagnosticsPanelSoon(){
  clearTimeout(diagnosticsHideTimer);
  diagnosticsHideTimer=setTimeout(()=>{
    if(!diagnosticsPinned)closeDiagnosticsPanel();
  },120);
}

function toggleDiagnosticsPanel(evt){
  if(evt)evt.stopPropagation();
  closeSettingsMenu();
  const panel=document.getElementById('diagnosticsPanel');
  const shouldOpen=!(panel&&panel.classList.contains('open')&&diagnosticsPinned);
  if(shouldOpen){
    diagnosticsPinned=true;
    showDiagnosticsPanel();
  }else{
    closeDiagnosticsPanel();
  }
}

function toggleSettingsMenu(evt){
  if(evt)evt.stopPropagation();
  closeDiagnosticsPanel();
  const menu=document.getElementById('settingsMenu');
  const toggle=document.getElementById('settingsToggle');
  const shouldOpen=!(menu&&menu.classList.contains('open'));
  if(menu)menu.classList.toggle('open',shouldOpen);
  if(toggle)toggle.classList.toggle('active',shouldOpen);
  setExpanded('settingsToggle',shouldOpen);
}

function closeTransientPanels(){
  closeSettingsMenu();
  closeDiagnosticsPanel();
}

function openDashboardDialog(id){
  closeTransientPanels();
  openDialog(id);
}

function syncNetworkForm(d){
  if(!apDirty){
    document.getElementById('apSSID').value=d.apSSID||'';
    document.getElementById('apPass').value=d.apPassword||'';
  }
  document.getElementById('upstreamEnable').checked=!!d.upstreamEnable;
  const savedNetworks=Array.isArray(d.upstreamNetworks)?d.upstreamNetworks:[];
  let scanSavedStateChanged=false;
  scanResults.forEach(net=>{
    const nextSaved=savedNetworks.some(saved=>saved.ssid===net.ssid);
    if(net.saved!==nextSaved){
      net.saved=nextSaved;
      scanSavedStateChanged=true;
    }
  });
  if(scanSavedStateChanged){
    refreshScanResultsSelect();
  }
  renderSavedNetworks(savedNetworks);
}

function syncDnsForm(d){
  if(dnsDirty)return;
  document.getElementById('dnsWhitelistEnable').checked=!!d.dnsWhitelistEnable;
  document.getElementById('dnsAllowlist').value=d.dnsAllowlist||'';
  document.getElementById('dnsBlocklist').value=d.dnsBlocklist||'';
}

function setNetMessage(text,type){
  const msg=document.getElementById('netMsg');
  msg.textContent=text;
  msg.className='msg'+(type?' '+type:'');
}

function setApMessage(text,type){
  const msg=document.getElementById('apMsg');
  msg.textContent=text;
  msg.className='msg'+(type?' '+type:'');
}

function normalizeDomain(domain){
  let normalized=(domain||'').trim().toLowerCase();
  while(normalized.endsWith('.'))normalized=normalized.slice(0,-1);
  return normalized;
}

function getDnsRulesFromTextarea(id){
  return (document.getElementById(id).value||'')
    .split(/[\s,;]+/)
    .map(normalizeDomain)
    .filter(Boolean);
}

function ruleMatchesDomain(domain,rule){
  if(!domain||!rule)return false;
  return domain===rule||(domain.length>rule.length&&domain.endsWith('.'+rule));
}

function isDomainAlreadyAllowed(domain){
  const normalizedDomain=normalizeDomain(domain);
  if(!normalizedDomain)return false;
  return getDnsRulesFromTextarea('dnsAllowlist').some(rule=>ruleMatchesDomain(normalizedDomain,rule));
}

function isDomainBlockedByBlacklist(domain){
  const normalizedDomain=normalizeDomain(domain);
  if(!normalizedDomain)return false;
  return getDnsRulesFromTextarea('dnsBlocklist').some(rule=>ruleMatchesDomain(normalizedDomain,rule));
}

function renderScanResults(){
  const select=document.getElementById('scanResults');
  const current=select.value;
  select.innerHTML='';

  if(!scanResults.length){
    const opt=document.createElement('option');
    opt.value='';
    opt.textContent='点击“搜索热点”查看附近可用热点';
    select.appendChild(opt);
    syncPickerButton('scanResults');
    return;
  }

  const placeholder=document.createElement('option');
  placeholder.value='';
  placeholder.textContent='请选择要保存的热点';
  select.appendChild(placeholder);

  scanResults.forEach(net=>{
    const opt=document.createElement('option');
    opt.value=net.ssid;
    let label=net.ssid;
    if(typeof net.rssi==='number')label+=' · '+net.rssi+' dBm';
    if(net.saved)label+=' · 已保存';
    opt.textContent=label;
    select.appendChild(opt);
  });

  if(scanResults.some(net=>net.ssid===current)){
    select.value=current;
  }
  syncPickerButton('scanResults');
}

function refreshScanResultsSelect(force){
  const select=document.getElementById('scanResults');
  if(!force&&document.activeElement===select){
    pendingScanResultsRender=true;
    return;
  }
  pendingScanResultsRender=false;
  renderScanResults();
}

function appendTag(parent,text,className){
  const tag=document.createElement('span');
  tag.className='tag'+(className?' '+className:'');
  tag.textContent=text;
  parent.appendChild(tag);
}

function renderSavedNetworks(networks){
  const wrap=document.getElementById('savedNetworks');
  wrap.innerHTML='';

  if(!Array.isArray(networks)||!networks.length){
    const empty=document.createElement('div');
    empty.className='empty-box';
    empty.textContent='还没有保存热点。先搜索附近热点，再保存需要自动连接的候选热点。';
    wrap.appendChild(empty);
    return;
  }

  networks.forEach(net=>{
    const item=document.createElement('div');
    item.className='saved-item';

    const main=document.createElement('div');
    main.className='saved-main';

    const name=document.createElement('div');
    name.className='saved-name';
    name.textContent=net.ssid;
    main.appendChild(name);

    const tags=document.createElement('div');
    tags.className='saved-tags';
    if(net.connected)appendTag(tags,'已连接','ok');
    else if(net.active)appendTag(tags,'连接中','busy');
    else appendTag(tags,'已保存','');
    if(!net.hasPass)appendTag(tags,'无密码','warn');
    main.appendChild(tags);

    const delBtn=document.createElement('button');
    delBtn.className='ghost-btn small-btn';
    delBtn.textContent='删除';
    delBtn.onclick=()=>deleteSavedUpstream(net.ssid);

    item.appendChild(main);
    item.appendChild(delBtn);
    wrap.appendChild(item);
  });
}

function formatRelativeTime(seconds){
  const delta=Math.max(0,seconds||0);
  if(delta<60)return delta+'秒前';
  if(delta<3600)return Math.floor(delta/60)+'分前';
  if(delta<86400)return Math.floor(delta/3600)+'小时前';
  return Math.floor(delta/86400)+'天前';
}

function renderBlockedDnsRequests(requests,currentUptime){
  const wrap=document.getElementById('dnsBlockedList');
  wrap.innerHTML='';

  if(!Array.isArray(requests)||!requests.length){
    const empty=document.createElement('div');
    empty.className='empty-box';
    empty.textContent='暂时没有被拦截域名统计。';
    wrap.appendChild(empty);
    return;
  }

  requests.forEach(item=>{
    const row=document.createElement('div');
    row.className='saved-item';
    const normalizedDomain=normalizeDomain(item.domain);
    const blockedByBlacklist=isDomainBlockedByBlacklist(normalizedDomain);
    const alreadyAllowed=isDomainAlreadyAllowed(normalizedDomain);

    const main=document.createElement('div');
    main.className='saved-main';

    const name=document.createElement('div');
    name.className='saved-name';
    name.textContent=item.domain||'(未知域名)';
    main.appendChild(name);

    const tags=document.createElement('div');
    tags.className='saved-tags';
    appendTag(tags,String(item.count||0)+'次','warn');
    appendTag(tags,formatRelativeTime((currentUptime||0)-(item.lastBlockedAt||0)),'busy');
    main.appendChild(tags);

    const addBtn=document.createElement('button');
    addBtn.className='ghost-btn small-btn';
    addBtn.textContent=blockedByBlacklist?'已在黑名单':(alreadyAllowed?'已在白名单':'加入白名单');
    addBtn.disabled=blockedByBlacklist||alreadyAllowed||!normalizedDomain;
    addBtn.onclick=()=>addBlockedDomainToAllowlist(normalizedDomain);

    row.appendChild(main);
    row.appendChild(addBtn);
    wrap.appendChild(row);
  });
}

function poll(){
  fetch('/api/status').then(r=>r.json()).then(d=>{
    updateCanActivity(d);
    setTextIfPresent('sErrors',d.errors);
    let u=d.uptime;
    let h=Math.floor(u/3600),m=Math.floor((u%3600)/60),s=u%60;
    setTextIfPresent('sUptime',h>0?h+'时'+m+'分':m>0?m+'分'+s+'秒':s+'秒');

    updateCanStatus(d);
    updateVehicleSpeedTelemetry(d);

    let fsdEl=document.getElementById('sFSD');
    if(fsdEl){
      fsdEl.textContent=d.fsdTriggered?'是':'否';
      fsdEl.className=(d.fsdTriggered?'status-yes':'status-no')+' status-text';
    }

    let thermalClass='status-ok';
    if(d.thermalProtect)thermalClass='status-err';
    else if((d.thermalStatus||'').includes('降频')||(d.thermalStatus||'').includes('偏高'))thermalClass='status-warn';
    let signalClass=getSignalClass(d.upstreamRSSI);

    document.getElementById('fsdEnable').checked=!!d.fsdEnable;
    document.getElementById('hwMode').value=d.hwMode;
    document.getElementById('speedProfile').value=d.speedProfile;
    document.getElementById('profileMode').value=d.profileMode?'1':'0';
    document.getElementById('isaChime').checked=!!d.isaChime;
    document.getElementById('emergencyDet').checked=!!d.emergencyDet;
    document.getElementById('chinaMode').checked=!!d.chinaMode;

    syncPickerButton('hwMode');
    syncPickerButton('speedProfile');
    syncPickerButton('profileMode');
    syncPickerButton('scanResults');

    syncNetworkForm(d);
    syncDnsForm(d);
    setStatusText('sUpstream',d.upstreamStatus||'--',d.upstreamConnected?'status-ok':(d.upstreamEnable?'status-err':'status-no'));
    setWideStatusText('sCurrentUpstream',d.connectedUpstreamSSID||d.upstreamSSID||'--',d.upstreamConnected?'status-ok':'status-no');
    setStatusText('sSavedUpstreams',String(d.upstreamSavedCount||0),d.upstreamSavedCount?'status-ok':'status-no');
    setStatusText('sUpstreamRSSI',typeof d.upstreamRSSI==='number'&&Number.isFinite(d.upstreamRSSI)?String(d.upstreamRSSI)+' dBm':'--',signalClass);
    setStatusText('sUpstreamSignal',d.upstreamSignal||'--',signalClass);
    setStatusText('sWiFiChannel',d.wifiChannel?String(d.wifiChannel):'--',d.wifiChannel?'status-ok':'status-no');
    setStatusText('sAPClients',String(d.apClients||0),(d.apClients||0)>1?'status-warn':'status-ok');
    setStatusText('sUpstreamIP',d.upstreamIP||'--',d.upstreamConnected?'status-ok':'status-no');
    setStatusText('sNAT',d.natStatus||'--',d.natEnabled?'status-ok':(d.upstreamConnected?'status-err':'status-no'));
    setStatusText('sAP',d.apSSID||'--','status-ok');
    setStatusText('sAPIP',d.apIP||'--','status-ok');
    setWideStatusText('sDNSMode',d.dnsWhitelistEnable?'已启用':'未启用',d.dnsWhitelistEnable?'status-ok':'status-no');
    setStatusText('sDNSCount',String(d.dnsWhitelistCount||0),d.dnsWhitelistCount?'status-ok':'status-no');
    setStatusText('sDNSBlockCount',String(d.dnsBlacklistCount||0),d.dnsBlacklistCount?'status-err':'status-no');
    setStatusText('sDNSBlocked',String(d.dnsBlockedCount||0),d.dnsBlockedCount?'status-err':'status-no');
    setWideStatusText('sChipTemp',formatChipTemp(d.chipTempC,d.chipTempAvgC),thermalClass);
    setWideStatusText('sThermal',d.thermalStatus||'--',thermalClass);
    latestBlockedDnsRequests=Array.isArray(d.dnsBlockedRequests)?d.dnsBlockedRequests:[];
    latestStatusUptime=d.uptime||0;
    renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
    syncDashboardSummary(d);
  }).catch(()=>{});
}

function setVal(key,val){
  fetch('/api/set?'+key+'='+val).catch(()=>{});
  syncDashboardSummary();
}

function getSelectDisplayText(select){
  if(!select||!select.options.length)return '请选择';
  const option=select.options[select.selectedIndex>=0?select.selectedIndex:0];
  return option&&option.textContent?option.textContent:'请选择';
}

function syncPickerButton(selectId){
  const select=document.getElementById(selectId);
  if(!select)return;
  const btnId=select.dataset.pickerTrigger;
  if(!btnId)return;
  const btn=document.getElementById(btnId);
  if(!btn)return;
  btn.textContent=getSelectDisplayText(select);
  btn.disabled=!!select.disabled;
}

function openPicker(selectId){
  const select=document.getElementById(selectId);
  if(!select||select.disabled)return;
  activePickerId=selectId;
  document.getElementById('pickerTitle').textContent=select.dataset.pickerTitle||'请选择';
  const body=document.getElementById('pickerBody');
  body.innerHTML='';
  for(let i=0;i<select.options.length;i++){
    const option=select.options[i];
    if(option.disabled)continue;
    const btn=document.createElement('button');
    btn.type='button';
    btn.className='picker-option'+(option.value===select.value?' active':'');
    btn.textContent=option.textContent;
    btn.onclick=()=>choosePickerValue(selectId,option.value);
    body.appendChild(btn);
  }
  document.getElementById('pickerModal').classList.add('open');
}

function choosePickerValue(selectId,value){
  const select=document.getElementById(selectId);
  if(!select)return;
  select.value=value;
  syncPickerButton(selectId);
  select.dispatchEvent(new Event('change',{bubbles:true}));
  syncDashboardSummary();
  closePicker();
}

function closePicker(evt){
  if(evt&&evt.target&&evt.target!==document.getElementById('pickerModal'))return;
  activePickerId='';
  document.getElementById('pickerModal').classList.remove('open');
}

function setUpstreamEnabled(enabled){
  setNetMessage('保存中...','');
  fetch('/api/set?upstreamEnable='+(enabled?'1':'0')).then(r=>{
    if(!r.ok)throw new Error('save failed');
    return r.text();
  }).then(()=>{
    setNetMessage(enabled?'热点接入已启用':'热点接入已关闭','ok');
    poll();
  }).catch(()=>{
    setNetMessage('保存失败','err');
    poll();
  });
}

function saveApConfig(){
  const ssid=(document.getElementById('apSSID').value||'').trim();
  const pass=document.getElementById('apPass').value||'';
  if(!ssid){
    setApMessage('热点名称不能为空','err');
    return;
  }
  if(ssid.length>32){
    setApMessage('热点名称最多 32 个字符','err');
    return;
  }
  if(pass.length<8||pass.length>63){
    setApMessage('热点密码长度必须为 8-63 个字符','err');
    return;
  }
  const params=new URLSearchParams();
  params.set('apSSID',ssid);
  params.set('apPass',pass);
  setApMessage('保存中，热点将重新启动...','');
  fetch('/api/set?'+params.toString()).then(async r=>{
    if(!r.ok){
      const txt=await r.text();
      throw new Error(txt||'save failed');
    }
    return r.text();
  }).then(()=>{
    apDirty=false;
    setApMessage('本地热点设置已保存，约 1 秒后会切换到新的名称和密码','ok');
  }).catch(err=>{
    setApMessage(err.message||'保存失败','err');
  });
}

function scanUpstreamNetworks(){
  const btn=document.getElementById('scanBtn');
  btn.disabled=true;
  setNetMessage('搜索中...','');

  fetch('/api/upstream/scan').then(r=>{
    if(!r.ok){
      return r.text().then(t=>{throw new Error(t||'scan failed');});
    }
    return r.json();
  }).then(d=>{
    scanResults=Array.isArray(d.results)?d.results:[];
    refreshScanResultsSelect(true);
    setNetMessage(scanResults.length?'已更新附近热点':'没有搜索到可用热点','ok');
  }).catch(err=>{
    setNetMessage(err.message||'搜索失败','err');
  }).finally(()=>{
    btn.disabled=false;
  });
}

function saveSelectedUpstream(){
  const ssid=document.getElementById('scanResults').value;
  const pass=document.getElementById('upstreamPass').value;

  if(!ssid){
    setNetMessage('请先选择要保存的热点','err');
    return;
  }

  const params=new URLSearchParams();
  params.set('ssid',ssid);
  if(pass)params.set('pass',pass);

  setNetMessage('保存中...','');

  fetch('/api/upstream/add?'+params.toString()).then(r=>{
    if(!r.ok){
      return r.text().then(t=>{throw new Error(t||'save failed');});
    }
    return r.text();
  }).then(()=>{
    document.getElementById('upstreamPass').value='';
    setNetMessage(document.getElementById('upstreamEnable').checked?'热点已保存，设备会自动切换到可连接的热点':'热点已保存，启用后会自动连接','ok');
    poll();
  }).catch(err=>{
    setNetMessage(err.message||'保存失败','err');
  });
}

function deleteSavedUpstream(ssid){
  if(!window.confirm('确定删除这个已保存热点吗？'))return;

  setNetMessage('删除中...','');
  fetch('/api/upstream/delete?ssid='+encodeURIComponent(ssid)).then(r=>{
    if(!r.ok){
      return r.text().then(t=>{throw new Error(t||'delete failed');});
    }
    return r.text();
  }).then(()=>{
    setNetMessage('已删除热点','ok');
    poll();
  }).catch(err=>{
    setNetMessage(err.message||'删除失败','err');
  });
}

['hwMode','speedProfile','profileMode','scanResults'].forEach(syncPickerButton);
syncDashboardSummary();

document.addEventListener('keydown',evt=>{
  if(evt.key!=='Escape')return;
  closeTransientPanels();
  closePicker();
  document.querySelectorAll('.dialog-modal.open').forEach(dialog=>dialog.classList.remove('open'));
});

document.addEventListener('click',evt=>{
  if(evt.target&&evt.target.closest&&evt.target.closest('.hud-popover-wrap'))return;
  closeTransientPanels();
});

function persistDnsRules(successText){
  const msg=document.getElementById('dnsMsg');
  const params=new URLSearchParams();

  params.set('dnsWhitelistEnable',document.getElementById('dnsWhitelistEnable').checked?'1':'0');
  params.set('dnsAllowlist',document.getElementById('dnsAllowlist').value.trim());
  params.set('dnsBlocklist',document.getElementById('dnsBlocklist').value.trim());

  msg.textContent='保存中...';
  msg.className='msg';

  fetch('/api/set?'+params.toString()).then(r=>{
    if(!r.ok)throw new Error('save failed');
    return r.text();
  }).then(()=>{
    dnsDirty=false;
    msg.textContent=successText||'DNS 规则已保存';
    msg.className='msg ok';
    poll();
  }).catch(()=>{
    msg.textContent='保存失败';
    msg.className='msg err';
  });
}

function saveDns(){
  persistDnsRules('DNS 规则已保存');
}

function addBlockedDomainToAllowlist(domain){
  const normalizedDomain=normalizeDomain(domain);
  const msg=document.getElementById('dnsMsg');

  if(!normalizedDomain){
    msg.textContent='域名无效，无法加入白名单';
    msg.className='msg err';
    return;
  }

  if(isDomainAlreadyAllowed(normalizedDomain)){
    msg.textContent='这个域名已经在白名单里了';
    msg.className='msg ok';
    renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
    return;
  }

  if(isDomainBlockedByBlacklist(normalizedDomain)){
    msg.textContent='这个域名已在黑名单里，黑名单优先，请先移除黑名单规则';
    msg.className='msg err';
    renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
    return;
  }

  const textarea=document.getElementById('dnsAllowlist');
  const current=textarea.value.trim();
  textarea.value=current?current+'\n'+normalizedDomain:normalizedDomain;
  dnsDirty=true;
  renderBlockedDnsRequests(latestBlockedDnsRequests,latestStatusUptime);
  persistDnsRules('已加入白名单: '+normalizedDomain);
}

function clearBlockedDns(){
  const msg=document.getElementById('dnsMsg');
  msg.textContent='清空中...';
  msg.className='msg';

  fetch('/api/dns/blocked/clear').then(r=>{
    if(!r.ok)throw new Error('clear failed');
    return r.text();
  }).then(()=>{
    msg.textContent='拦截记录已清空';
    msg.className='msg ok';
    poll();
  }).catch(()=>{
    msg.textContent='清空失败';
    msg.className='msg err';
  });
}

function formatBytes(bytes){
  if(typeof bytes!=='number'||!Number.isFinite(bytes)||bytes<0)return '--';
  if(bytes<1024)return String(Math.round(bytes))+' B';
  if(bytes<1024*1024)return (bytes/1024).toFixed(bytes<10*1024?1:0)+' KB';
  return (bytes/(1024*1024)).toFixed(bytes<10*1024*1024?2:1)+' MB';
}

function setOtaMessage(text,kind){
  const msg=document.getElementById('otaMsg');
  if(!msg)return;
  msg.textContent=text||'';
  msg.className='msg'+(kind?' '+kind:'');
}

function setOtaProgress(percent){
  const prog=document.getElementById('progWrap');
  const bar=document.getElementById('progBar');
  if(!prog||!bar)return;
  prog.style.display='block';
  bar.style.width=Math.max(0,Math.min(100,percent))+'%';
}

function setOtaUploadEnabled(enabled){
  const btn=document.getElementById('uploadBtn');
  const file=document.getElementById('fwFile').files[0];
  if(btn)btn.disabled=enabled?!file:true;
}

function stopOtaTrace(){
  otaTraceGeneration++;
  if(otaTraceTimer){
    clearTimeout(otaTraceTimer);
    otaTraceTimer=0;
  }
  if(otaTraceController){
    otaTraceController.abort();
    otaTraceController=null;
  }
  otaTraceStartedAt=0;
  otaTraceClientUploadComplete=false;
  otaTraceSawLikelySuccessPhase=false;
}

function scheduleOtaTrace(traceId){
  otaTraceTimer=setTimeout(()=>traceOtaStatus(traceId),OTA_TRACE_POLL_MS);
}

function parseJsonSafe(text){
  if(!text)return null;
  try{
    return JSON.parse(text);
  }catch(_err){
    return null;
  }
}

function getWrongOtaFileMessage(file){
  if(!file||!file.name)return '';
  const lower=file.name.trim().toLowerCase();
  if(lower.endsWith('full.bin'))return 'WebUI OTA 只能上传 firmware.bin，不能直接上传 full.bin。';
  if(lower.endsWith('bootloader.bin')||lower.endsWith('partitions.bin'))return 'bootloader.bin / partitions.bin 不能通过 WebUI OTA 更新。请选择应用固件 firmware.bin。';
  return '';
}

function buildOtaStatusLines(status){
  const lines=[];
  if(status&&status.errorMessage)lines.push(status.errorMessage);
  if(status&&typeof status.bytesReceived==='number'&&Number.isFinite(status.bytesReceived)&&status.bytesReceived>0){
    let progress='设备侧已接收 '+formatBytes(status.bytesReceived);
    if(typeof status.totalBytes==='number'&&Number.isFinite(status.totalBytes)&&status.totalBytes>0){
      progress+=' / HTTP 请求体 '+formatBytes(status.totalBytes);
    }
    lines.push(progress);
  }
  if(status&&status.hint)lines.push(status.hint);
  return lines.filter(Boolean);
}

function renderOtaStatus(status,fallbackMessage){
  const phase=status&&status.phase?status.phase:'idle';
  const hasBytes=!!status&&typeof status.bytesReceived==='number'&&Number.isFinite(status.bytesReceived)&&status.bytesReceived>0;
  const hasTotal=!!status&&typeof status.totalBytes==='number'&&Number.isFinite(status.totalBytes)&&status.totalBytes>0;
  if(hasBytes&&hasTotal)setOtaProgress(Math.round(status.bytesReceived/status.totalBytes*100));

  switch(phase){
    case 'uploading':
      setOtaMessage(['设备正在接收固件...'].concat(buildOtaStatusLines(status)).join('\n'),'');
      return false;
    case 'finishing':
      setOtaProgress(100);
      setOtaMessage(['固件已传到设备，正在完成校验...'].concat(buildOtaStatusLines(status)).join('\n'),'');
      return false;
    case 'success-rebooting':
      setOtaProgress(100);
      setOtaMessage(buildOtaStatusLines(status).join('\n')||'固件写入完成，设备正在重启。','ok');
      stopOtaTrace();
      return true;
    case 'failed-begin':
    case 'failed-write':
    case 'failed-end':
    case 'aborted':
      setOtaMessage(buildOtaStatusLines(status).join('\n')||fallbackMessage||'升级失败','err');
      setOtaUploadEnabled(true);
      stopOtaTrace();
      return true;
    case 'idle':
    default:
      if(fallbackMessage){
        setOtaMessage(fallbackMessage,'err');
        setOtaUploadEnabled(true);
      }
      stopOtaTrace();
      return true;
  }
}

function finishOtaTraceAfterIdle(){
  const lines=[];
  if(otaTraceClientUploadComplete||otaTraceSawLikelySuccessPhase){
    setOtaProgress(100);
    lines.push('设备已重新上线，上一轮 OTA 响应大概率被重启打断。');
    lines.push('如果页面功能正常，本次升级通常已经完成。');
    setOtaMessage(lines.join('\n'),'');
  }else{
    lines.push('设备已重新上线，但本次 OTA 状态已在重启后丢失。');
    lines.push('浏览器端上传没有完整结束，更像是链路中断或设备异常重启。');
    lines.push('建议重试一次，并结合串口日志确认原因。');
    setOtaMessage(lines.join('\n'),'');
  }
  setOtaUploadEnabled(true);
  stopOtaTrace();
}

function traceOtaStatus(traceId){
  if(traceId!==otaTraceGeneration)return;
  const controller=typeof AbortController==='function'?new AbortController():null;
  otaTraceController=controller;
  const requestInit={cache:'no-store'};
  if(controller)requestInit.signal=controller.signal;

  fetch('/api/ota/status',requestInit).then(r=>{
    if(traceId!==otaTraceGeneration)return null;
    if(!r.ok)throw new Error('status unavailable');
    return r.json();
  }).then(status=>{
    if(traceId!==otaTraceGeneration||!status)return;
    if(otaTraceController===controller)otaTraceController=null;
    const phase=status&&status.phase?status.phase:'idle';
    if(phase==='finishing'||phase==='success-rebooting'){
      otaTraceSawLikelySuccessPhase=true;
    }
    if(phase==='idle'){
      finishOtaTraceAfterIdle();
      return;
    }
    if(renderOtaStatus(status,''))return;
    if(Date.now()-otaTraceStartedAt>OTA_TRACE_TIMEOUT_MS){
      const lines=['设备暂时没有返回明确失败原因。'].concat(buildOtaStatusLines(status));
      lines.push('请结合串口日志继续排查。');
      setOtaMessage(lines.join('\n'),'err');
      setOtaUploadEnabled(true);
      stopOtaTrace();
      return;
    }
    scheduleOtaTrace(traceId);
  }).catch(err=>{
    if(traceId!==otaTraceGeneration)return;
    if(otaTraceController===controller)otaTraceController=null;
    if(err&&err.name==='AbortError')return;
    if(Date.now()-otaTraceStartedAt>OTA_TRACE_TIMEOUT_MS){
      setOtaMessage('连接已断开，但设备长时间没有恢复在线，未能拿到诊断结果。请查看串口日志。','err');
      setOtaUploadEnabled(true);
      stopOtaTrace();
      return;
    }
    setOtaMessage('连接已断开，正在等待设备重新上线并回传诊断信息...','err');
    scheduleOtaTrace(traceId);
  });
}

function startOtaTrace(initialMessage){
  stopOtaTrace();
  otaTraceStartedAt=Date.now();
  otaTraceClientUploadComplete=otaClientUploadComplete;
  if(initialMessage)setOtaMessage(initialMessage,'err');
  traceOtaStatus(otaTraceGeneration);
}

function fileChosen(inp){
  const file=inp.files[0];
  document.getElementById('fileName').textContent=file?file.name:'未选择文件';
  stopOtaTrace();
  setOtaProgress(0);
  document.getElementById('progWrap').style.display='none';
  const wrongFileMessage=getWrongOtaFileMessage(file);
  if(wrongFileMessage){
    setOtaMessage(wrongFileMessage,'err');
    document.getElementById('uploadBtn').disabled=true;
    return;
  }
  setOtaMessage('','');
  document.getElementById('uploadBtn').disabled=!file;
}

function doOTA(){
  let file=document.getElementById('fwFile').files[0];
  if(!file)return;
  const wrongFileMessage=getWrongOtaFileMessage(file);
  if(wrongFileMessage){
    setOtaMessage(wrongFileMessage,'err');
    return;
  }
  stopOtaTrace();
  otaClientUploadComplete=false;
  let xhr=new XMLHttpRequest();
  setOtaProgress(0);
  setOtaMessage('开始上传，设备正在准备 OTA...','');
  document.getElementById('uploadBtn').disabled=true;
  xhr.upload.addEventListener('progress',e=>{
    if(e.lengthComputable){
      const percent=Math.round(e.loaded/e.total*100);
      otaClientUploadComplete=e.loaded>=e.total||percent>=100;
      setOtaProgress(percent);
      setOtaMessage('浏览器正在上传固件...','');
    }
  });
  xhr.onload=function(){
    const result=parseJsonSafe(xhr.responseText);
    if(result&&typeof result==='object'){
      renderOtaStatus(result,xhr.status===200?'固件写入完成，设备正在重启。':'升级失败');
      return;
    }
    if(xhr.status===200){
      setOtaProgress(100);
      setOtaMessage('固件写入完成，设备正在重启。','ok');
      return;
    }
    setOtaMessage('升级失败，设备没有返回可解析的诊断信息。','err');
    setOtaUploadEnabled(true);
  };
  xhr.onerror=function(){
    startOtaTrace('连接已中断，正在读取设备侧诊断信息...');
  };
  let form=new FormData();
  form.append('firmware',file);
  xhr.open('POST','/api/ota');
  xhr.send(form);
}

setInterval(poll,1000);
poll();
</script>
  </body>
</html>
)rawliteral";
